"""
ddns_writer.py
--------------
Dynamic DNS update support.
Backend: ddclient (pkg install ddclient)
Config:  /usr/local/etc/ddclient.conf

Credentials are stored encrypted via secret_store.encrypt_secret().
The config file is written with 0600 permissions (secrets inside).

Also handles RFC2136 DNS updates via nsupdate (BIND-utils or drill).

Public API
----------
generate_ddclient_conf(conn)     -> str
validate_ddns(clients)           -> list[str]
apply_ddns(conn)                 -> dict
get_ddns_status()                -> dict
test_ddns_update(client)         -> dict
generate_nsupdate_script(client) -> str
validate_rfc2136(client)         -> list[str]
"""

import ipaddress
import os
import re
import sys

from app.secret_store import decrypt_secret, mask_secret

_DDCLIENT_CONF = "/usr/local/etc/ddclient.conf"
_DDCLIENT_PID  = "/var/run/ddclient/ddclient.pid"

_SUPPORTED_PROVIDERS = {
    "cloudflare", "dyndns2", "namecheap", "noip", "afraid",
    "loopia", "easydns", "spdyn", "dnsexit", "dnsomatic",
    "google", "he", "custom",
}

_RFC2136_ALGORITHMS = {
    "hmac-md5", "hmac-sha1", "hmac-sha224",
    "hmac-sha256", "hmac-sha384", "hmac-sha512",
}


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def validate_ddns(clients: list) -> list:
    errors = []
    for i, client in enumerate(clients or []):
        label = client.get("hostname") or f"client[{i}]"
        if not client.get("hostname"):
            errors.append(f"Client {i}: hostname is required.")
        if not client.get("service_type"):
            errors.append(f"[{label}] Service type is required.")
        elif client["service_type"] not in _SUPPORTED_PROVIDERS:
            errors.append(f"[{label}] Unknown service type: {client['service_type']!r}.")
        if not client.get("username"):
            errors.append(f"[{label}] Username is required.")
    return errors


def validate_rfc2136(client: dict) -> list:
    errors = []
    zone   = (client.get("zone") or "").strip()
    server = (client.get("server") or "").strip()
    keyname = (client.get("key_name") or "").strip()
    key_enc = (client.get("key") or "").strip()
    alg    = (client.get("key_algorithm") or "").lower().strip()
    host   = (client.get("hostname") or "").strip()

    if not host:
        errors.append("Hostname is required.")
    if not zone:
        errors.append("Zone is required.")
    if not server:
        errors.append("DNS server is required.")
    else:
        try:
            ipaddress.ip_address(server)
        except ValueError:
            # Accept hostnames too
            if " " in server:
                errors.append(f"DNS server {server!r} does not look valid.")

    if not keyname:
        errors.append("TSIG key name is required.")
    if not key_enc:
        errors.append("TSIG key secret is required.")
    else:
        if key_enc.startswith("hash:"):
            errors.append("TSIG key is stored with a one-way hash and cannot be used — re-enter it.")

    if alg and alg not in _RFC2136_ALGORITHMS:
        errors.append(f"Unknown TSIG algorithm {alg!r}. Supported: {', '.join(sorted(_RFC2136_ALGORITHMS))}.")

    return errors


# ---------------------------------------------------------------------------
# ddclient config generator
# ---------------------------------------------------------------------------

def generate_ddclient_conf(conn) -> str:
    import json
    rows = conn.execute(
        "SELECT value_json FROM service_state WHERE key_name='dynamic_dns_clients'"
    ).fetchone()
    clients = json.loads(rows["value_json"]) if rows else []

    lines = [
        "# ============================================================",
        "# Smart Shield — auto-generated ddclient.conf",
        "# Generated by app/services/ddns_writer.py",
        "# Backend: ddclient (pkg install ddclient)",
        "# SECRETS ARE IN THIS FILE — permissions 0600",
        "# DO NOT EDIT MANUALLY",
        "# ============================================================",
        "",
        "daemon=300",
        "syslog=yes",
        "pid=/var/run/ddclient/ddclient.pid",
        "ssl=yes",
        "",
    ]

    for client in clients:
        if client.get("disabled"):
            continue
        svc      = (client.get("service_type") or "").lower()
        hostname = (client.get("hostname") or "").strip()
        username = (client.get("username") or "").strip()
        pw_enc   = (client.get("password") or "").strip()
        password = decrypt_secret(pw_enc) if pw_enc else ""
        iface    = (client.get("interface") or "").strip()
        desc     = (client.get("description") or "").strip()

        if not hostname:
            continue

        if desc:
            lines.append(f"# {desc}")
        lines.append(f"protocol={svc}")
        if iface:
            lines.append(f"use=if, if={iface}")
        else:
            lines.append("use=web, web=checkip.dyndns.org/, web-skip='Current IP Address: '")
        if username:
            lines.append(f"login={username}")
        if password:
            lines.append(f"password={password}")
        lines.append(hostname)
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Apply
# ---------------------------------------------------------------------------

def apply_ddns(conn) -> dict:
    import json
    rows = conn.execute(
        "SELECT value_json FROM service_state WHERE key_name='dynamic_dns_clients'"
    ).fetchone()
    clients = json.loads(rows["value_json"]) if rows else []

    errors = validate_ddns([c for c in clients if not c.get("disabled")])
    conf   = generate_ddclient_conf(conn)

    if errors:
        return {"ok": False, "message": "Validation failed: " + " | ".join(errors), "conf": conf}

    if not sys.platform.startswith("freebsd"):
        return {"ok": True, "rolled_back": False,
                "message": "Non-FreeBSD — ddclient.conf generated but not written.", "conf": conf}

    from app.services.config_file_utils import apply_with_rollback
    from app.services.service_manager import service_action, sysrc_set
    sysrc_set("ddclient_enable", "YES")

    def _restart():
        return service_action("ddclient", "restart")

    result = apply_with_rollback(_DDCLIENT_CONF, conf, _restart, mode=0o600)
    return {**result, "conf": conf}


# ---------------------------------------------------------------------------
# Status
# ---------------------------------------------------------------------------

def get_ddns_status() -> dict:
    if not sys.platform.startswith("freebsd"):
        return {"running": False, "state": "dry-run", "message": "Non-FreeBSD host."}
    try:
        running = os.path.exists(_DDCLIENT_PID)
        state   = "running" if running else "stopped"
        return {"running": running, "state": state, "message": ""}
    except Exception as exc:
        return {"running": False, "state": "error", "message": str(exc)}


def force_ddns_update() -> dict:
    """
    Force ddclient to immediately update all DDNS providers (``ddclient -force``).
    Returns ``{"ok": bool, "message": str, "output": str}``.
    On non-FreeBSD: dry-run, returns ok=True without running anything.
    """
    if not sys.platform.startswith("freebsd"):
        return {"ok": True, "message": "Non-FreeBSD — DDNS force-update skipped.", "output": ""}

    import shutil
    if not shutil.which("ddclient"):
        return {"ok": False, "message": "ddclient binary not found.", "output": ""}

    try:
        from app.services.network_service import run_command
        result = run_command(["ddclient", "-force"], check=False, timeout_seconds=30)
        ok  = result.returncode == 0
        out = (result.stdout or result.stderr or "").strip()
        return {
            "ok":      ok,
            "message": "DDNS force-update completed." if ok else f"ddclient exited {result.returncode}.",
            "output":  out,
        }
    except Exception as exc:
        return {"ok": False, "message": str(exc), "output": ""}


# ---------------------------------------------------------------------------
# RFC2136 nsupdate script generator
# ---------------------------------------------------------------------------

def generate_nsupdate_script(client: dict) -> str:
    """
    Generate an nsupdate command script for an RFC2136 client.
    The caller is responsible for piping this to nsupdate stdin.
    Key secret is decrypted for inclusion — never log the result.
    """
    server  = (client.get("server") or "").strip()
    zone    = (client.get("zone") or "").strip()
    host    = (client.get("hostname") or "").strip()
    ttl     = str(client.get("ttl") or "300")
    keyname = (client.get("key_name") or "").strip()
    key_enc = (client.get("key") or "").strip()
    key     = decrypt_secret(key_enc) if key_enc else ""
    alg     = (client.get("key_algorithm") or "hmac-sha256").lower()
    rtype   = (client.get("record_type") or "A").upper()
    ip      = (client.get("current_ip") or "").strip()

    lines = []
    if server:
        lines.append(f"server {server}")
    if keyname and key:
        lines.append(f"key hmac-md5:{keyname} {key}")
    lines += [
        f"zone {zone}",
        f"update delete {host}. {rtype}",
    ]
    if ip:
        lines.append(f"update add {host}. {ttl} {rtype} {ip}")
    lines.append("send")
    return "\n".join(lines) + "\n"
