"""
dhcp_writer.py
--------------
Generates /usr/local/etc/dhcpd.conf from Smart Shield's SQLite DHCP tables
and optionally reloads the isc-dhcpd service.

Public API
----------
generate_dhcpd_conf(conn)  -> str
write_dhcpd_conf(conn)     -> {"ok": bool, "message": str, "conf": str}
"""

import sys
import textwrap
from app.services.network_service import FreeBSDNetworkError

_DHCPD_CONF_PATH = "/usr/local/etc/dhcpd.conf"


def _rows(conn, sql, params=()):
    cur = conn.cursor()
    cur.execute(sql, params)
    return [dict(r) for r in cur.fetchall()]


def _dns_list(raw: str) -> list:
    return [s.strip() for s in (raw or "").replace(";", ",").split(",") if s.strip()]


def generate_dhcpd_conf(conn) -> str:
    lines = [
        "# ============================================================",
        "# Smart Shield — auto-generated dhcpd.conf",
        "# Generated by app/services/dhcp_writer.py",
        "# DO NOT EDIT MANUALLY",
        "# ============================================================",
        "",
        "default-lease-time 86400;",
        "max-lease-time 86400;",
        "authoritative;",
        "",
    ]

    pools = _rows(conn, "SELECT * FROM dhcp_pools WHERE enabled=1 ORDER BY interface_type")
    for pool in pools:
        itype = (pool.get("interface_type") or "LAN").upper()

        # Find the LAN interface address to determine the subnet
        if itype == "LAN":
            iface_rows = _rows(conn, "SELECT ipv4_address, assigned_port FROM lan_config LIMIT 1")
        else:
            iface_rows = _rows(conn, "SELECT ipv4_address, assigned_port FROM wan_config LIMIT 1")

        iface_row  = iface_rows[0] if iface_rows else {}
        iface_cidr = iface_row.get("ipv4_address") or ""
        iface_port = iface_row.get("assigned_port") or ""

        # Derive subnet + netmask from interface address
        subnet = "0.0.0.0"
        netmask = "255.255.255.0"
        try:
            import ipaddress
            net = ipaddress.ip_interface(iface_cidr).network
            subnet  = str(net.network_address)
            netmask = str(net.netmask)
        except Exception:
            pass

        start_ip = pool.get("start_ip") or ""
        end_ip   = pool.get("end_ip") or ""
        gateway  = pool.get("gateway_ip") or ""
        dns_raw  = pool.get("dns_servers") or ""
        lease    = pool.get("lease_time") or 86400
        dns_list = _dns_list(dns_raw)

        if not start_ip or not end_ip or subnet == "0.0.0.0":
            continue

        lines.append(f"# {itype} pool ({iface_port or itype})")
        lines.append(f"subnet {subnet} netmask {netmask} {{")
        lines.append(f"    range {start_ip} {end_ip};")
        if gateway:
            lines.append(f"    option routers {gateway};")
        if dns_list:
            lines.append(f"    option domain-name-servers {', '.join(dns_list)};")
        lines.append(f"    default-lease-time {lease};")
        lines.append(f"    max-lease-time {lease};")
        lines.append("}")
        lines.append("")

    # Static leases
    leases = _rows(conn, "SELECT * FROM static_leases ORDER BY interface_type, hostname")
    if leases:
        lines.append("# ── Static leases ──")
        for lease in leases:
            hostname = (lease.get("hostname") or "").strip()
            mac      = (lease.get("mac_address") or "").strip().lower()
            ip       = (lease.get("ip_address") or "").strip()
            if not mac or not ip:
                continue
            host_id = hostname.replace(" ", "_") if hostname else mac.replace(":", "")
            lines.append(f"host {host_id} {{")
            lines.append(f"    hardware ethernet {mac};")
            lines.append(f"    fixed-address {ip};")
            if hostname:
                lines.append(f"    option host-name \"{hostname}\";")
            lines.append("}")
            lines.append("")

    return "\n".join(lines)


def write_dhcpd_conf(conn) -> dict:
    conf = generate_dhcpd_conf(conn)

    if not sys.platform.startswith("freebsd"):
        return {"ok": True, "message": "Non-FreeBSD — dhcpd.conf generated but not written.", "conf": conf}

    try:
        with open(_DHCPD_CONF_PATH, "w") as fh:
            fh.write(conf)
        return {"ok": True, "message": f"Written to {_DHCPD_CONF_PATH}", "conf": conf}
    except OSError as exc:
        return {"ok": False, "message": str(exc), "conf": conf}
