"""
dns_writer.py
-------------
Generates /usr/local/etc/unbound/unbound.conf from Smart Shield's service_state
table (DNS Resolver / DNS Forwarder settings).

Public API
----------
generate_unbound_conf(conn)         -> str
validate_unbound_conf(text)         -> (bool, str)   (ok, error_message)
write_unbound_conf(conn)            -> {"ok", "message", "conf"}
apply_unbound(conn)                 -> {"ok", "message", "conf"}
get_unbound_status()                -> {"running", "state", "message"}
test_dns_resolution(hostname, server) -> {"ok", "ip", "message", "method"}
"""

import json
import os
import sys
import tempfile

_UNBOUND_CONF_PATH       = "/usr/local/etc/unbound/unbound.conf"
_UNBOUND_KNOWN_GOOD_PATH = "/usr/local/etc/unbound/unbound.conf.known_good"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _rows(conn, sql, params=()):
    cur = conn.cursor()
    cur.execute(sql, params)
    return [dict(r) for r in cur.fetchall()]


def _load_service_state(conn, key: str) -> dict:
    rows = _rows(conn, "SELECT value_json FROM service_state WHERE key_name=?", (key,))
    if not rows:
        return {}
    try:
        return json.loads(rows[0]["value_json"] or "{}")
    except (json.JSONDecodeError, KeyError):
        return {}


def _upstream_dns(conn) -> list:
    """Load upstream DNS servers from config file or return defaults."""
    try:
        cfg_path = os.getenv("SMARTSHIELD_CONFIG_PATH", "config.json")
        if os.path.exists(cfg_path):
            with open(cfg_path) as f:
                cfg = json.load(f)
            servers = [s for s in (cfg.get("dns_servers") or []) if s]
            if servers:
                return servers
    except Exception:
        pass
    env_dns = os.getenv("SMARTSHIELD_DEFAULT_DNS", "").strip()
    if env_dns:
        return [s.strip() for s in env_dns.split(",") if s.strip()]
    return ["1.1.1.1", "8.8.8.8"]


def _lan_ip(conn) -> str:
    rows = _rows(conn, "SELECT ipv4_address FROM lan_config LIMIT 1")
    if not rows:
        return "127.0.0.1"
    cidr = (rows[0].get("ipv4_address") or "").strip()
    try:
        import ipaddress
        return str(ipaddress.ip_interface(cidr).ip)
    except Exception:
        return cidr.split("/")[0] if "/" in cidr else (cidr or "127.0.0.1")


def _lan_net(conn) -> str:
    rows = _rows(conn, "SELECT ipv4_address FROM lan_config LIMIT 1")
    if not rows:
        return ""
    cidr = (rows[0].get("ipv4_address") or "").strip()
    try:
        import ipaddress
        return str(ipaddress.ip_interface(cidr).network)
    except Exception:
        return ""


# ---------------------------------------------------------------------------
# Config generator
# ---------------------------------------------------------------------------

def generate_unbound_conf(conn) -> str:
    """
    Build a complete unbound.conf from DB state.
    Merge order: base settings → access controls → host overrides
                 → DNS filter zones → Web filter zones → App filter zones
                 → forward zone
    """
    resolver = _load_service_state(conn, "dns_resolver")
    upstream  = _upstream_dns(conn)
    iface_ip  = _lan_ip(conn) or "127.0.0.1"
    lan_subnet = _lan_net(conn)

    lines = [
        "# ============================================================",
        "# Smart Shield — auto-generated unbound.conf",
        "# Generated by app/services/dns_writer.py",
        "# DO NOT EDIT MANUALLY",
        "# ============================================================",
        "",
        "server:",
        f"    interface: {iface_ip}",
        "    interface: 127.0.0.1",
        "    port: 53",
        "    do-ip4: yes",
        "    do-ip6: no",
        "    do-udp: yes",
        "    do-tcp: yes",
        "",
        "    access-control: 127.0.0.0/8 allow",
        "    access-control: ::1 allow",
    ]

    if lan_subnet:
        lines.append(f"    access-control: {lan_subnet} allow")

    # Whitelist view: pre-compute overrides so access-control-view is only added when view exists.
    try:
        whitelisted_ips = [
            r["ip_address"]
            for r in conn.execute(
                "SELECT ip_address FROM tracked_hosts WHERE is_whitelisted=1"
            ).fetchall()
        ]
    except Exception:
        whitelisted_ips = []

    whitelist_overrides: list = []
    if whitelisted_ips:
        try:
            import importlib as _il
            for _mn, _fn in [
                ("app.services.dns_filter", "generate_dns_whitelist_overrides"),
                ("app.services.web_filter", "generate_web_whitelist_overrides"),
                ("app.services.app_filter", "generate_app_filter_dns_overrides"),
            ]:
                whitelist_overrides.extend(getattr(_il.import_module(_mn), _fn)(conn))
        except Exception:
            whitelist_overrides = []

    # Emit access-control-view lines NOW (inside server block) only if view block will be written
    if whitelist_overrides:
        for _ip in whitelisted_ips:
            lines.append(f"    access-control-view: {_ip}/32 whitelist_view")

    # Phase 3.3 — policy_exemption_view: clients flagged is_policy_exempt get a
    # view with NO local-zone overrides, so blocked domains resolve normally.
    # The view block itself is emitted below (after the forward-zone) only when
    # there is at least one exempt client. Each /32 access-control-view line
    # routes that client into the empty view; Unbound applies global server-block
    # local-zones for everyone else.
    try:
        policy_exempt_ips = [
            r["ip_address"]
            for r in conn.execute(
                "SELECT ip_address FROM tracked_hosts WHERE is_policy_exempt=1"
            ).fetchall()
        ]
    except Exception:
        policy_exempt_ips = []

    if policy_exempt_ips:
        for _ip in policy_exempt_ips:
            lines.append(f"    access-control-view: {_ip}/32 policy_exemption_view")

    # SIEM DNS query logging (off by default — admin must enable)
    siem_dns = _load_service_state(conn, "siem_settings")
    dns_query_logging = bool(siem_dns.get("dns_query_logging", False))

    lines += [
        "",
        "    hide-identity: yes",
        "    hide-version: yes",
        "    harden-glue: yes",
        "    harden-dnssec-stripped: yes",
        "    use-caps-for-id: no",
        "    cache-min-ttl: 0",
        "    cache-max-ttl: 86400",
        "    prefetch: yes",
        "    num-threads: 1",
        "    msg-cache-slabs: 1",
        "    rrset-cache-slabs: 1",
        "    infra-cache-slabs: 1",
        "    key-cache-slabs: 1",
        "",
        "    # Private address suppression",
        "    private-address: 192.168.0.0/16",
        "    private-address: 172.16.0.0/12",
        "    private-address: 10.0.0.0/8",
        "",
    ]

    if dns_query_logging:
        lines += [
            "    # SIEM DNS query logging",
            "    log-queries: yes",
            '    logfile: "/var/log/unbound/query.log"',
            "",
        ]

    # Static host overrides
    host_overrides = resolver.get("host_overrides") or []
    if host_overrides:
        lines.append("    # ── Host overrides ──")
        for entry in host_overrides:
            host   = (entry.get("host")   or "").strip()
            domain = (entry.get("domain") or "").strip()
            ip     = (entry.get("ip")     or "").strip()
            if host and domain and ip:
                fqdn = f"{host}.{domain}"
                lines.append(f'    local-data: "{fqdn}. A {ip}"')
                lines.append(f'    local-data-ptr: "{ip} {fqdn}"')
        lines.append("")

    # Content Policy zones — single deduplicated pass over the unified
    # DomainPolicy map so an entry shared by DNS / Web / App filters emits
    # exactly one local-zone record (unbound-checkconf rejects duplicates).
    try:
        from app.services.content_policy import (
            emit_unbound_policy_zones, get_block_page_ip,
        )
        zones = emit_unbound_policy_zones(conn, get_block_page_ip(conn))
        if zones:
            lines.append("    # ── Content Policy (Security Profiles) ──")
            lines.extend(zones)
            lines.append("")
    except Exception:
        pass

    # Phase 4.2 — block known DNS-over-HTTPS provider endpoints so clients
    # can't trivially bypass DNS filtering by enabling DoH in their browser.
    # Gated on content_policy_settings.block_known_doh (default ON whenever
    # any content/DNS/web/app rule is active).
    try:
        from app.services.dns_filter import generate_doh_block_zones
        doh_zones = generate_doh_block_zones(conn)
        if doh_zones:
            lines.append("    # ── DNS-over-HTTPS provider blocks (Phase 4.2) ──")
            lines.extend(doh_zones)
            lines.append("")
    except Exception:
        pass

    # Forward zone
    lines.append("forward-zone:")
    lines.append('    name: "."')
    for dns in upstream:
        lines.append(f"    forward-addr: {dns}")
    lines.append("")

    # Whitelist view — transparent overrides for "allow whitelist only" rules.
    if whitelist_overrides:
        lines.append("view:")
        lines.append('    name: "whitelist_view"')
        lines.extend(whitelist_overrides)
        lines.append("")

    # Policy-exemption view — emits `local-zone: ... transparent` for every
    # currently-blocked domain so clients in tracked_hosts.is_policy_exempt
    # bypass content/DNS/app blocks. Unbound's default view-first: no semantics
    # mean the view's local-zones take precedence over server-scope ones for
    # matching clients; transparent tells Unbound to forward the query
    # upstream rather than synthesizing the block answer.
    if policy_exempt_ips:
        try:
            from app.services.content_policy import emit_policy_exemption_overrides
            exemption_overrides = emit_policy_exemption_overrides(conn)
        except Exception:
            exemption_overrides = []
        lines.append("view:")
        lines.append('    name: "policy_exemption_view"')
        if exemption_overrides:
            lines.extend(exemption_overrides)
        else:
            # No blocked domains right now — emit a harmless placeholder so the
            # view block isn't empty (unbound-checkconf accepts empty views,
            # but keeping a comment makes the generated file easier to read).
            lines.append("    # No blocked domains currently — view is a no-op.")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Validation via unbound-checkconf
# ---------------------------------------------------------------------------

def validate_unbound_conf(text: str) -> tuple:
    """
    Validate unbound.conf syntax using ``unbound-checkconf``.
    Returns ``(True, "")`` on success, ``(False, error)`` on failure.
    On non-FreeBSD or if unbound-checkconf is not installed, returns
    ``(True, "skipped")``.
    """
    if not sys.platform.startswith("freebsd"):
        return (True, "skipped-non-freebsd")

    import shutil
    if not shutil.which("unbound-checkconf"):
        return (True, "skipped-unbound-checkconf-not-found")

    tmp_path = None
    try:
        from app.services.network_service import run_command, FreeBSDNetworkError
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".conf", delete=False, prefix="ss_unbound_"
        ) as f:
            f.write(text)
            tmp_path = f.name

        result = run_command(["unbound-checkconf", tmp_path], check=False)
        ok  = result.returncode == 0
        msg = (result.stderr or result.stdout or "").strip()
        return (ok, msg)
    except Exception as exc:
        return (False, str(exc))
    finally:
        if tmp_path:
            try:
                os.unlink(tmp_path)
            except Exception:
                pass


# ---------------------------------------------------------------------------
# Known-good rollback helpers
# ---------------------------------------------------------------------------

def _save_known_good_unbound() -> bool:
    """Copy current unbound.conf to the known-good backup. Returns True on success."""
    try:
        if os.path.exists(_UNBOUND_CONF_PATH):
            with open(_UNBOUND_CONF_PATH) as fh:
                current = fh.read()
            os.makedirs(os.path.dirname(_UNBOUND_KNOWN_GOOD_PATH), exist_ok=True)
            with open(_UNBOUND_KNOWN_GOOD_PATH, "w") as fh:
                fh.write(current)
        return True
    except OSError:
        return False


def _unbound_is_running() -> bool:
    """Best-effort check: is the unbound daemon currently running?"""
    from app.services.service_manager import service_action
    r = service_action("unbound", "status")
    return r.get("ok", False) and "is running" in (r.get("message") or "").lower()


def _start_or_reload_unbound() -> dict:
    """
    Reload unbound when it's running, otherwise start it. A fresh install has
    unbound enabled in rc.conf but the daemon was never up, so a bare `reload`
    would error with "unbound not running? (check ...unbound.pid)".
    """
    from app.services.service_manager import service_action
    action = "reload" if _unbound_is_running() else "start"
    return service_action("unbound", action)


def _restart_unbound() -> dict:
    """Full restart of Unbound. Unlike ``reload`` (which only re-reads
    caches/zones/ACLs), a restart re-opens listening sockets — required when the
    set of bound interfaces changes (e.g. the install-time 127.0.0.1 bootstrap
    config gaining the LAN IP, or a LAN-IP change). See ``apply_unbound``."""
    from app.services.service_manager import service_action
    return service_action("unbound", "restart")


def _rollback_unbound() -> dict:
    """Restore the known-good unbound.conf and reload/start Unbound."""
    if not os.path.exists(_UNBOUND_KNOWN_GOOD_PATH):
        return {"ok": False, "message": "No known-good unbound.conf backup found."}
    try:
        with open(_UNBOUND_KNOWN_GOOD_PATH) as fh:
            old_conf = fh.read()
        with open(_UNBOUND_CONF_PATH, "w") as fh:
            fh.write(old_conf)
        result = _start_or_reload_unbound()
        if result["ok"]:
            return {"ok": True, "message": "Rolled back to last known-good unbound.conf."}
        return {"ok": False, "message": f"Rollback file restored but reload failed: {result['message']}"}
    except OSError as exc:
        return {"ok": False, "message": f"Rollback failed: {exc}"}


# ---------------------------------------------------------------------------
# Write
# ---------------------------------------------------------------------------

def write_unbound_conf(conn) -> dict:
    conf = generate_unbound_conf(conn)
    if not sys.platform.startswith("freebsd"):
        return {"ok": True, "message": "Non-FreeBSD — unbound.conf generated but not written.", "conf": conf}
    # Phase 5.4: atomic write so a crash mid-flush leaves the previous valid
    # unbound.conf intact rather than a truncated file Unbound refuses to load.
    try:
        from app.services.config_file_utils import atomic_write
        atomic_write(_UNBOUND_CONF_PATH, conf)
        return {"ok": True, "message": f"Written to {_UNBOUND_CONF_PATH}", "conf": conf}
    except OSError as exc:
        return {"ok": False, "message": str(exc), "conf": conf}


# ---------------------------------------------------------------------------
# Apply (write + checkconf + reload)
# ---------------------------------------------------------------------------

def apply_unbound(conn) -> dict:
    """
    Generate unbound.conf, validate with unbound-checkconf when available,
    write to disk, and reload Unbound.

    On non-FreeBSD: generate + validate only (no file writes, no service restart).
    Returns ``{"ok": bool, "message": str, "conf": str}``.
    """
    conf = generate_unbound_conf(conn)

    # Validate
    ok, err = validate_unbound_conf(conf)
    if not ok:
        return {"ok": False, "message": f"unbound-checkconf error: {err}", "conf": conf}

    # Non-FreeBSD dry-run
    if not sys.platform.startswith("freebsd"):
        return {"ok": True, "message": "Non-FreeBSD — conf generated (validation OK).", "conf": conf}

    # Backup current config as known-good before overwriting
    _save_known_good_unbound()

    # Write atomically (Phase 5.4) — same rationale as write_unbound_conf above.
    try:
        from app.services.config_file_utils import atomic_write
        atomic_write(_UNBOUND_CONF_PATH, conf)
    except OSError as exc:
        return {"ok": False, "message": str(exc), "conf": conf}

    # Enable in rc.conf for reboot persistence, then reload (or start if dead).
    from app.services.service_manager import sysrc_set
    sysrc_set("unbound_enable", "YES")
    result = _start_or_reload_unbound()
    if not result["ok"]:
        rb = _rollback_unbound()
        rb_msg = rb.get("message", "rollback status unknown")
        return {
            "ok": False,
            "message": f"Unbound reload failed ({result['message']}). {rb_msg}",
            "conf": conf,
            "rolled_back": rb["ok"],
        }

    # A successful rc `start`/`reload` exit code does NOT prove the daemon
    # actually bound :53 — a bad chroot/permissions setup, or the FreeBSD base
    # `local_unbound` shadowing the pkg `unbound`, can let the rc script exit 0
    # while Unbound dies on startup. If we trusted the exit code alone, a router
    # would ship with working NAT but dead DNS: LAN clients can ping IPs yet
    # can't browse, and reload_all_services / the setup wizard would wrongly
    # report the box as "ready". Verify the resolver is truly up before
    # returning success. Skipped under network dry-run (no live work was done,
    # so there's nothing to bind).
    from app.services.network_service import is_network_dry_run
    if not is_network_dry_run():
        status = get_unbound_status()
        if not status.get("running"):
            return {
                "ok": False,
                "message": (
                    f"Unbound {result['message']}, but the daemon is not listening "
                    f"on :53 ({status.get('message') or 'no status'}). Check "
                    f"`unbound-checkconf {_UNBOUND_CONF_PATH}` and confirm the pkg "
                    f"`unbound` service (not base `local_unbound`) owns port 53."
                ),
                "conf": conf,
                "rolled_back": False,
            }

        # Running is not enough: a `reload` re-reads the config but does NOT
        # re-open listening sockets, so an Unbound that started on the
        # install-time 127.0.0.1-only bootstrap config stays bound to loopback
        # even after we write a config that adds the LAN IP. LAN clients are
        # handed this box as their resolver via DHCP, so "running on 127.0.0.1"
        # leaves the whole LAN unable to browse. When the LAN IP isn't actually
        # being served, escalate from reload to a full restart (which re-binds),
        # then re-probe with a short bounded retry — Unbound takes a beat to bind
        # after start (mirrors the probe in routes/setup.py:_wizard_verify).
        import time as _time
        lan_ip = _lan_ip(conn)
        if lan_ip and lan_ip != "127.0.0.1" and not unbound_listening_on_lan(conn):
            result = _restart_unbound()
            bound = False
            for _attempt in range(3):
                if unbound_listening_on_lan(conn):
                    bound = True
                    break
                if _attempt < 2:
                    _time.sleep(1)
            if not result.get("ok") or not bound:
                rb = _rollback_unbound()
                return {
                    "ok": False,
                    "message": (
                        f"Unbound restarted ({result.get('message', 'no status')}) "
                        f"but is still not listening on the LAN IP {lan_ip}:53. "
                        f"Check `unbound-checkconf {_UNBOUND_CONF_PATH}` and confirm "
                        f"the pkg `unbound` service (not base `local_unbound`) owns "
                        f"port 53. {rb.get('message', '')}".strip()
                    ),
                    "conf": conf,
                    "rolled_back": rb.get("ok", False),
                }

    return {
        "ok": True,
        "message": result["message"],
        "conf": conf,
        "rolled_back": False,
    }


# ---------------------------------------------------------------------------
# Service status
# ---------------------------------------------------------------------------

def get_unbound_status() -> dict:
    """Return the live Unbound running state."""
    if not sys.platform.startswith("freebsd"):
        return {"running": False, "state": "dry-run", "message": "Non-FreeBSD host."}
    from app.services.service_manager import service_action
    result = service_action("unbound", "status")
    msg    = result.get("message", "")
    running = result.get("ok", False) and "running" in msg.lower()
    return {
        "running": running,
        "state":   "running" if running else "stopped",
        "message": msg,
    }


# ---------------------------------------------------------------------------
# LAN-serving checks
# ---------------------------------------------------------------------------
# `get_unbound_status()` only tells us the daemon is *running* — which is true
# even for the install-time bootstrap config that binds 127.0.0.1 only. LAN
# clients are pointed at the appliance's LAN IP for DNS (DHCP), so "running on
# localhost" still leaves the whole LAN without name resolution. These helpers
# answer the question that actually matters: can a LAN client resolve through us?

def unbound_listening_on_lan(conn) -> bool:
    """True when Unbound is bound to the LAN IP (or 0.0.0.0) on :53 — not merely
    127.0.0.1. Off-FreeBSD we can't inspect sockets, so return True so dev hosts
    and the test suite are unaffected."""
    if not sys.platform.startswith("freebsd"):
        return True
    lan_ip = _lan_ip(conn)
    if not lan_ip or lan_ip == "127.0.0.1":
        return False
    try:
        from app.services.network_service import run_command
        r = run_command(["sockstat", "-4", "-l"], check=False, timeout_seconds=5)
        targets = {f"{lan_ip}:53", "*:53"}
        for line in (r.stdout or "").splitlines():
            # sockstat columns are whitespace-separated; the local address is a
            # standalone token, so token equality avoids substring false hits
            # (e.g. 192.168.1.1:53 vs 192.168.1.1:5353).
            if targets & set(line.split()):
                return True
    except Exception:
        return False
    return False


def unbound_serving_lan(conn) -> bool:
    """Stronger check: Unbound both listens on the LAN IP:53 AND answers a query
    there. Used by the recovery path / watchdog. Off-FreeBSD returns True."""
    if not sys.platform.startswith("freebsd"):
        return True
    if not unbound_listening_on_lan(conn):
        return False
    res = test_dns_resolution("example.com", server=_lan_ip(conn))
    return bool(res.get("ok"))


# ---------------------------------------------------------------------------
# Self-healing recovery (shared by the GUI apply path and the DNS watchdog)
# ---------------------------------------------------------------------------

def _disable_base_local_unbound() -> None:
    """Ensure the FreeBSD base ``local_unbound`` is disabled so the pkg
    ``unbound`` (the one Smart Shield manages) owns :53. A running base resolver
    can win the port and let the pkg rc script exit 0 with the real resolver
    dead. Best-effort, FreeBSD-only."""
    if not sys.platform.startswith("freebsd"):
        return
    try:
        from app.services.service_manager import sysrc_set, service_action
        sysrc_set("local_unbound_enable", "NO")
        service_action("local_unbound", "stop")   # usually already stopped — ignore result
    except Exception:
        pass


def recover_dns_service(conn, actor: str = "watchdog") -> dict:
    """Bring Unbound back to a state where it actually serves the LAN, idempotently.

    No-op when it is already serving. Otherwise: disable the base resolver so it
    can't shadow :53, run the full ``apply_unbound`` (regenerates the LAN-binding
    config, validates with unbound-checkconf, enables in rc.conf, starts, and
    verifies the daemon is up), and on success re-apply PF so the content-policy
    DNS funnel re-engages (pf_generator gates it on ``unbound_listening_on_lan``).

    Returns ``{"ok", "skipped"?, "reason"?, "message", "service_message"?}``.
    Safe to call from any thread — uses only the passed connection + service
    helpers.
    """
    if unbound_serving_lan(conn):
        return {"ok": True, "skipped": True, "reason": "already_serving",
                "message": "Unbound is already serving the LAN."}

    _disable_base_local_unbound()

    result = apply_unbound(conn)
    if not result.get("ok"):
        return {"ok": False, "reason": "apply_failed",
                "message": result.get("message", "apply_unbound failed"),
                "service_message": result.get("message", "")}

    # Resolver is back — re-apply PF so the fail-open DNS funnel re-engages.
    pf_msg = ""
    try:
        from app.services.pf_generator import reload_pf_rules
        pf = reload_pf_rules(conn)
        pf_msg = pf.get("message", "") if isinstance(pf, dict) else ""
    except Exception as exc:
        pf_msg = f"pf reload skipped: {exc}"

    return {"ok": True, "reason": "recovered",
            "message": f"Unbound recovered and serving the LAN. {pf_msg}".strip(),
            "service_message": result.get("message", "")}


# ---------------------------------------------------------------------------
# DNS resolution test
# ---------------------------------------------------------------------------

def test_dns_resolution(hostname: str, server: str = "127.0.0.1") -> dict:
    """
    Resolve *hostname* using the local resolver and return the result.

    Tries (in order):
      1. ``drill`` (FreeBSD base, uses ldns)
      2. ``dig``   (bind-tools)
      3. Python's ``socket.getaddrinfo`` (always available)

    Returns ``{"ok": bool, "ip": str|None, "method": str, "message": str}``.
    """
    import shutil
    import socket

    hostname = (hostname or "").strip()
    if not hostname:
        return {"ok": False, "ip": None, "method": "none", "message": "No hostname provided."}

    # 1. drill
    if sys.platform.startswith("freebsd") and shutil.which("drill"):
        try:
            from app.services.network_service import run_command
            r = run_command(
                ["drill", "@" + server, hostname, "A"],
                check=False, timeout_seconds=5
            )
            if r.returncode == 0:
                for line in r.stdout.splitlines():
                    parts = line.split()
                    if len(parts) >= 5 and parts[3] == "A":
                        return {"ok": True, "ip": parts[4], "method": "drill", "message": ""}
                return {"ok": False, "ip": None, "method": "drill", "message": "No A record."}
        except Exception as exc:
            pass

    # 2. dig
    if shutil.which("dig"):
        try:
            from app.services.network_service import run_command
            r = run_command(
                ["dig", f"@{server}", "+short", hostname, "A"],
                check=False, timeout_seconds=5
            )
            if r.returncode == 0 and r.stdout.strip():
                ip = r.stdout.strip().splitlines()[0].strip()
                return {"ok": True, "ip": ip, "method": "dig", "message": ""}
        except Exception:
            pass

    # 3. Python socket (uses system resolver, ignores server param)
    try:
        info = socket.getaddrinfo(hostname, None, socket.AF_INET)
        if info:
            ip = info[0][4][0]
            return {
                "ok": True, "ip": ip, "method": "socket",
                "message": "Resolved via system resolver (server param ignored).",
            }
    except socket.gaierror as exc:
        return {"ok": False, "ip": None, "method": "socket", "message": str(exc)}

    return {"ok": False, "ip": None, "method": "none", "message": "All resolution methods failed."}
