"""
dns_writer.py
-------------
Generates /usr/local/etc/unbound/unbound.conf from Smart Shield's service_state
table (DNS Resolver / DNS Forwarder settings).

Public API
----------
generate_unbound_conf(conn)         -> str
validate_unbound_conf(text)         -> (bool, str)   (ok, error_message)
write_unbound_conf(conn)            -> {"ok", "message", "conf"}
apply_unbound(conn)                 -> {"ok", "message", "conf"}
get_unbound_status()                -> {"running", "state", "message"}
test_dns_resolution(hostname, server) -> {"ok", "ip", "message", "method"}
"""

import json
import os
import sys
import tempfile

_UNBOUND_CONF_PATH       = "/usr/local/etc/unbound/unbound.conf"
_UNBOUND_KNOWN_GOOD_PATH = "/usr/local/etc/unbound/unbound.conf.known_good"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _rows(conn, sql, params=()):
    cur = conn.cursor()
    cur.execute(sql, params)
    return [dict(r) for r in cur.fetchall()]


def _load_service_state(conn, key: str) -> dict:
    rows = _rows(conn, "SELECT value_json FROM service_state WHERE key_name=?", (key,))
    if not rows:
        return {}
    try:
        return json.loads(rows[0]["value_json"] or "{}")
    except (json.JSONDecodeError, KeyError):
        return {}


def _upstream_dns(conn) -> list:
    """Load upstream DNS servers from config file or return defaults."""
    try:
        cfg_path = os.getenv("SMARTSHIELD_CONFIG_PATH", "config.json")
        if os.path.exists(cfg_path):
            with open(cfg_path) as f:
                cfg = json.load(f)
            servers = [s for s in (cfg.get("dns_servers") or []) if s]
            if servers:
                return servers
    except Exception:
        pass
    return ["1.1.1.1", "8.8.8.8"]


def _lan_ip(conn) -> str:
    rows = _rows(conn, "SELECT ipv4_address FROM lan_config LIMIT 1")
    if not rows:
        return "127.0.0.1"
    cidr = (rows[0].get("ipv4_address") or "").strip()
    try:
        import ipaddress
        return str(ipaddress.ip_interface(cidr).ip)
    except Exception:
        return cidr.split("/")[0] if "/" in cidr else (cidr or "127.0.0.1")


def _lan_net(conn) -> str:
    rows = _rows(conn, "SELECT ipv4_address FROM lan_config LIMIT 1")
    if not rows:
        return ""
    cidr = (rows[0].get("ipv4_address") or "").strip()
    try:
        import ipaddress
        return str(ipaddress.ip_interface(cidr).network)
    except Exception:
        return ""


# ---------------------------------------------------------------------------
# Config generator
# ---------------------------------------------------------------------------

def generate_unbound_conf(conn) -> str:
    """
    Build a complete unbound.conf from DB state.
    Merge order: base settings → access controls → host overrides
                 → DNS filter zones → Web filter zones → App filter zones
                 → forward zone
    """
    resolver = _load_service_state(conn, "dns_resolver")
    upstream  = _upstream_dns(conn)
    iface_ip  = _lan_ip(conn) or "127.0.0.1"
    lan_subnet = _lan_net(conn)

    lines = [
        "# ============================================================",
        "# Smart Shield — auto-generated unbound.conf",
        "# Generated by app/services/dns_writer.py",
        "# DO NOT EDIT MANUALLY",
        "# ============================================================",
        "",
        "server:",
        f"    interface: {iface_ip}",
        "    interface: 127.0.0.1",
        "    port: 53",
        "    do-ip4: yes",
        "    do-ip6: no",
        "    do-udp: yes",
        "    do-tcp: yes",
        "",
        "    access-control: 127.0.0.0/8 allow",
        "    access-control: ::1 allow",
    ]

    if lan_subnet:
        lines.append(f"    access-control: {lan_subnet} allow")

    # Whitelist view: pre-compute overrides so access-control-view is only added when view exists.
    try:
        whitelisted_ips = [
            r["ip_address"]
            for r in conn.execute(
                "SELECT ip_address FROM tracked_hosts WHERE is_whitelisted=1"
            ).fetchall()
        ]
    except Exception:
        whitelisted_ips = []

    whitelist_overrides: list = []
    if whitelisted_ips:
        try:
            import importlib as _il
            for _mn, _fn in [
                ("app.services.dns_filter", "generate_dns_whitelist_overrides"),
                ("app.services.web_filter", "generate_web_whitelist_overrides"),
                ("app.services.app_filter", "generate_app_filter_dns_overrides"),
            ]:
                whitelist_overrides.extend(getattr(_il.import_module(_mn), _fn)(conn))
        except Exception:
            whitelist_overrides = []

    # Emit access-control-view lines NOW (inside server block) only if view block will be written
    if whitelist_overrides:
        for _ip in whitelisted_ips:
            lines.append(f"    access-control-view: {_ip}/32 whitelist_view")

    # SIEM DNS query logging (off by default — admin must enable)
    siem_dns = _load_service_state(conn, "siem_settings")
    dns_query_logging = bool(siem_dns.get("dns_query_logging", False))

    lines += [
        "",
        "    hide-identity: yes",
        "    hide-version: yes",
        "    harden-glue: yes",
        "    harden-dnssec-stripped: yes",
        "    use-caps-for-id: no",
        "    cache-min-ttl: 0",
        "    cache-max-ttl: 86400",
        "    prefetch: yes",
        "    num-threads: 1",
        "    msg-cache-slabs: 1",
        "    rrset-cache-slabs: 1",
        "    infra-cache-slabs: 1",
        "    key-cache-slabs: 1",
        "",
        "    # Private address suppression",
        "    private-address: 192.168.0.0/16",
        "    private-address: 172.16.0.0/12",
        "    private-address: 10.0.0.0/8",
        "",
    ]

    if dns_query_logging:
        lines += [
            "    # SIEM DNS query logging",
            "    log-queries: yes",
            '    logfile: "/var/log/unbound/query.log"',
            "",
        ]

    # Static host overrides
    host_overrides = resolver.get("host_overrides") or []
    if host_overrides:
        lines.append("    # ── Host overrides ──")
        for entry in host_overrides:
            host   = (entry.get("host")   or "").strip()
            domain = (entry.get("domain") or "").strip()
            ip     = (entry.get("ip")     or "").strip()
            if host and domain and ip:
                fqdn = f"{host}.{domain}"
                lines.append(f'    local-data: "{fqdn}. A {ip}"')
                lines.append(f'    local-data-ptr: "{ip} {fqdn}"')
        lines.append("")

    # DNS filter zones (Security Profiles)
    for module, fn_name, label in [
        ("app.services.dns_filter",  "generate_dns_filter_zones",  "DNS Filter"),
        ("app.services.web_filter",  "generate_web_filter_zones",  "Web Filter"),
        ("app.services.app_filter",  "generate_app_filter_dns_zones", "App Filter DNS"),
    ]:
        try:
            import importlib
            mod   = importlib.import_module(module)
            fn    = getattr(mod, fn_name)
            zones = fn(conn)
            if zones:
                lines.append(f"    # ── {label} (Security Profiles) ──")
                lines.extend(zones)
                lines.append("")
        except Exception:
            pass

    # Forward zone
    lines.append("forward-zone:")
    lines.append('    name: "."')
    for dns in upstream:
        lines.append(f"    forward-addr: {dns}")
    lines.append("")

    # Whitelist view — transparent overrides for "allow whitelist only" rules.
    if whitelist_overrides:
        lines.append("view:")
        lines.append('    name: "whitelist_view"')
        lines.extend(whitelist_overrides)
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Validation via unbound-checkconf
# ---------------------------------------------------------------------------

def validate_unbound_conf(text: str) -> tuple:
    """
    Validate unbound.conf syntax using ``unbound-checkconf``.
    Returns ``(True, "")`` on success, ``(False, error)`` on failure.
    On non-FreeBSD or if unbound-checkconf is not installed, returns
    ``(True, "skipped")``.
    """
    if not sys.platform.startswith("freebsd"):
        return (True, "skipped-non-freebsd")

    import shutil
    if not shutil.which("unbound-checkconf"):
        return (True, "skipped-unbound-checkconf-not-found")

    tmp_path = None
    try:
        from app.services.network_service import run_command, FreeBSDNetworkError
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".conf", delete=False, prefix="ss_unbound_"
        ) as f:
            f.write(text)
            tmp_path = f.name

        result = run_command(["unbound-checkconf", tmp_path], check=False)
        ok  = result.returncode == 0
        msg = (result.stderr or result.stdout or "").strip()
        return (ok, msg)
    except Exception as exc:
        return (False, str(exc))
    finally:
        if tmp_path:
            try:
                os.unlink(tmp_path)
            except Exception:
                pass


# ---------------------------------------------------------------------------
# Known-good rollback helpers
# ---------------------------------------------------------------------------

def _save_known_good_unbound() -> bool:
    """Copy current unbound.conf to the known-good backup. Returns True on success."""
    try:
        if os.path.exists(_UNBOUND_CONF_PATH):
            with open(_UNBOUND_CONF_PATH) as fh:
                current = fh.read()
            os.makedirs(os.path.dirname(_UNBOUND_KNOWN_GOOD_PATH), exist_ok=True)
            with open(_UNBOUND_KNOWN_GOOD_PATH, "w") as fh:
                fh.write(current)
        return True
    except OSError:
        return False


def _rollback_unbound() -> dict:
    """Restore the known-good unbound.conf and reload Unbound."""
    if not os.path.exists(_UNBOUND_KNOWN_GOOD_PATH):
        return {"ok": False, "message": "No known-good unbound.conf backup found."}
    try:
        with open(_UNBOUND_KNOWN_GOOD_PATH) as fh:
            old_conf = fh.read()
        with open(_UNBOUND_CONF_PATH, "w") as fh:
            fh.write(old_conf)
        from app.services.service_manager import service_action
        result = service_action("unbound", "reload")
        if result["ok"]:
            return {"ok": True, "message": "Rolled back to last known-good unbound.conf."}
        return {"ok": False, "message": f"Rollback file restored but reload failed: {result['message']}"}
    except OSError as exc:
        return {"ok": False, "message": f"Rollback failed: {exc}"}


# ---------------------------------------------------------------------------
# Write
# ---------------------------------------------------------------------------

def write_unbound_conf(conn) -> dict:
    conf = generate_unbound_conf(conn)
    if not sys.platform.startswith("freebsd"):
        return {"ok": True, "message": "Non-FreeBSD — unbound.conf generated but not written.", "conf": conf}
    os.makedirs(os.path.dirname(_UNBOUND_CONF_PATH), exist_ok=True)
    try:
        with open(_UNBOUND_CONF_PATH, "w") as fh:
            fh.write(conf)
        return {"ok": True, "message": f"Written to {_UNBOUND_CONF_PATH}", "conf": conf}
    except OSError as exc:
        return {"ok": False, "message": str(exc), "conf": conf}


# ---------------------------------------------------------------------------
# Apply (write + checkconf + reload)
# ---------------------------------------------------------------------------

def apply_unbound(conn) -> dict:
    """
    Generate unbound.conf, validate with unbound-checkconf when available,
    write to disk, and reload Unbound.

    On non-FreeBSD: generate + validate only (no file writes, no service restart).
    Returns ``{"ok": bool, "message": str, "conf": str}``.
    """
    conf = generate_unbound_conf(conn)

    # Validate
    ok, err = validate_unbound_conf(conf)
    if not ok:
        return {"ok": False, "message": f"unbound-checkconf error: {err}", "conf": conf}

    # Non-FreeBSD dry-run
    if not sys.platform.startswith("freebsd"):
        return {"ok": True, "message": "Non-FreeBSD — conf generated (validation OK).", "conf": conf}

    # Backup current config as known-good before overwriting
    _save_known_good_unbound()

    # Write
    os.makedirs(os.path.dirname(_UNBOUND_CONF_PATH), exist_ok=True)
    try:
        with open(_UNBOUND_CONF_PATH, "w") as fh:
            fh.write(conf)
    except OSError as exc:
        return {"ok": False, "message": str(exc), "conf": conf}

    # Enable in rc.conf for reboot persistence, then reload
    from app.services.service_manager import service_action, sysrc_set
    sysrc_set("unbound_enable", "YES")
    result = service_action("unbound", "reload")
    if not result["ok"]:
        rb = _rollback_unbound()
        rb_msg = rb.get("message", "rollback status unknown")
        return {
            "ok": False,
            "message": f"Unbound reload failed ({result['message']}). {rb_msg}",
            "conf": conf,
            "rolled_back": rb["ok"],
        }
    return {
        "ok": True,
        "message": result["message"],
        "conf": conf,
        "rolled_back": False,
    }


# ---------------------------------------------------------------------------
# Service status
# ---------------------------------------------------------------------------

def get_unbound_status() -> dict:
    """Return the live Unbound running state."""
    if not sys.platform.startswith("freebsd"):
        return {"running": False, "state": "dry-run", "message": "Non-FreeBSD host."}
    from app.services.service_manager import service_action
    result = service_action("unbound", "status")
    msg    = result.get("message", "")
    running = result.get("ok", False) and "running" in msg.lower()
    return {
        "running": running,
        "state":   "running" if running else "stopped",
        "message": msg,
    }


# ---------------------------------------------------------------------------
# DNS resolution test
# ---------------------------------------------------------------------------

def test_dns_resolution(hostname: str, server: str = "127.0.0.1") -> dict:
    """
    Resolve *hostname* using the local resolver and return the result.

    Tries (in order):
      1. ``drill`` (FreeBSD base, uses ldns)
      2. ``dig``   (bind-tools)
      3. Python's ``socket.getaddrinfo`` (always available)

    Returns ``{"ok": bool, "ip": str|None, "method": str, "message": str}``.
    """
    import shutil
    import socket

    hostname = (hostname or "").strip()
    if not hostname:
        return {"ok": False, "ip": None, "method": "none", "message": "No hostname provided."}

    # 1. drill
    if sys.platform.startswith("freebsd") and shutil.which("drill"):
        try:
            from app.services.network_service import run_command
            r = run_command(
                ["drill", "@" + server, hostname, "A"],
                check=False, timeout_seconds=5
            )
            if r.returncode == 0:
                for line in r.stdout.splitlines():
                    parts = line.split()
                    if len(parts) >= 5 and parts[3] == "A":
                        return {"ok": True, "ip": parts[4], "method": "drill", "message": ""}
                return {"ok": False, "ip": None, "method": "drill", "message": "No A record."}
        except Exception as exc:
            pass

    # 2. dig
    if shutil.which("dig"):
        try:
            from app.services.network_service import run_command
            r = run_command(
                ["dig", f"@{server}", "+short", hostname, "A"],
                check=False, timeout_seconds=5
            )
            if r.returncode == 0 and r.stdout.strip():
                ip = r.stdout.strip().splitlines()[0].strip()
                return {"ok": True, "ip": ip, "method": "dig", "message": ""}
        except Exception:
            pass

    # 3. Python socket (uses system resolver, ignores server param)
    try:
        info = socket.getaddrinfo(hostname, None, socket.AF_INET)
        if info:
            ip = info[0][4][0]
            return {
                "ok": True, "ip": ip, "method": "socket",
                "message": "Resolved via system resolver (server param ignored).",
            }
    except socket.gaierror as exc:
        return {"ok": False, "ip": None, "method": "socket", "message": str(exc)}

    return {"ok": False, "ip": None, "method": "none", "message": "All resolution methods failed."}
