"""
dns_writer.py
-------------
Generates /usr/local/etc/unbound/unbound.conf from Smart Shield's service_state
table (DNS Resolver / DNS Forwarder settings).

Public API
----------
generate_unbound_conf(conn)  -> str
write_unbound_conf(conn)     -> {"ok": bool, "message": str, "conf": str}
"""

import json
import sys

_UNBOUND_CONF_PATH = "/usr/local/etc/unbound/unbound.conf"


def _rows(conn, sql, params=()):
    cur = conn.cursor()
    cur.execute(sql, params)
    return [dict(r) for r in cur.fetchall()]


def _load_service_state(conn, key: str) -> dict:
    rows = _rows(conn, "SELECT value_json FROM service_state WHERE key_name=?", (key,))
    if not rows:
        return {}
    try:
        return json.loads(rows[0]["value_json"] or "{}")
    except (json.JSONDecodeError, KeyError):
        return {}


def _load_general_config(conn) -> dict:
    """Pull hostname + domain from config table or return defaults."""
    rows = _rows(conn, "SELECT value_json FROM service_state WHERE key_name='general_config' LIMIT 1")
    if rows:
        try:
            return json.loads(rows[0]["value_json"] or "{}")
        except Exception:
            pass
    return {"hostname": "smartshield", "domain": "home.arpa"}


def generate_unbound_conf(conn) -> str:
    resolver = _load_service_state(conn, "dns_resolver")
    forwarder = _load_service_state(conn, "dns_forwarder")

    # Pull DNS servers from general config
    general_rows = _rows(conn, "SELECT * FROM service_state WHERE key_name='general_config' LIMIT 1")
    upstream_dns = []

    # Also check general_setup config.json stored via system.py
    try:
        import os, json as _json
        cfg_path = os.getenv("SMARTSHIELD_CONFIG_PATH", "config.json")
        if os.path.exists(cfg_path):
            with open(cfg_path) as f:
                cfg = _json.load(f)
            upstream_dns = [s for s in (cfg.get("dns_servers") or []) if s]
    except Exception:
        pass

    if not upstream_dns:
        upstream_dns = ["1.1.1.1", "8.8.8.8"]

    # Pull LAN IP for local access
    lan_rows = _rows(conn, "SELECT ipv4_address FROM lan_config LIMIT 1")
    lan_ip = ""
    if lan_rows:
        cidr = (lan_rows[0].get("ipv4_address") or "").strip()
        try:
            import ipaddress
            lan_ip = str(ipaddress.ip_interface(cidr).ip)
        except Exception:
            lan_ip = cidr.split("/")[0] if "/" in cidr else cidr

    interface_ip = lan_ip or "127.0.0.1"

    lines = [
        "# ============================================================",
        "# Smart Shield — auto-generated unbound.conf",
        "# Generated by app/services/dns_writer.py",
        "# DO NOT EDIT MANUALLY",
        "# ============================================================",
        "",
        "server:",
        f"    interface: {interface_ip}",
        "    interface: 127.0.0.1",
        "    port: 53",
        "    do-ip4: yes",
        "    do-ip6: no",
        "    do-udp: yes",
        "    do-tcp: yes",
        "",
        "    access-control: 127.0.0.0/8 allow",
        "    access-control: ::1 allow",
    ]

    # Allow LAN subnet
    if lan_ip:
        lan_rows2 = _rows(conn, "SELECT ipv4_address FROM lan_config LIMIT 1")
        if lan_rows2:
            cidr = (lan_rows2[0].get("ipv4_address") or "").strip()
            try:
                import ipaddress
                net = str(ipaddress.ip_interface(cidr).network)
                lines.append(f"    access-control: {net} allow")
            except Exception:
                pass

    lines += [
        "",
        "    hide-identity: yes",
        "    hide-version: yes",
        "    harden-glue: yes",
        "    harden-dnssec-stripped: yes",
        "    use-caps-for-id: no",
        "    cache-min-ttl: 0",
        "    cache-max-ttl: 86400",
        "    prefetch: yes",
        "    num-threads: 1",
        "    msg-cache-slabs: 1",
        "    rrset-cache-slabs: 1",
        "    infra-cache-slabs: 1",
        "    key-cache-slabs: 1",
        "",
        "    # Private address reverse lookup suppression",
        "    private-address: 192.168.0.0/16",
        "    private-address: 172.16.0.0/12",
        "    private-address: 10.0.0.0/8",
        "",
    ]

    # Static host overrides from DNS resolver state
    host_overrides = resolver.get("host_overrides") or []
    if host_overrides:
        lines.append("    # ── Host overrides ──")
        for entry in host_overrides:
            host = entry.get("host", "")
            domain = entry.get("domain", "")
            ip = entry.get("ip", "")
            if host and domain and ip:
                lines.append(f"    local-data: \"{host}.{domain}. A {ip}\"")
                lines.append(f"    local-data-ptr: \"{ip} {host}.{domain}\"")
        lines.append("")

    # Forward zone to upstream resolvers
    lines.append("forward-zone:")
    lines.append("    name: \".\"")
    for dns in upstream_dns:
        lines.append(f"    forward-addr: {dns}")
    lines.append("")

    return "\n".join(lines)


def write_unbound_conf(conn) -> dict:
    conf = generate_unbound_conf(conn)

    if not sys.platform.startswith("freebsd"):
        return {"ok": True, "message": "Non-FreeBSD — unbound.conf generated but not written.", "conf": conf}

    import os
    os.makedirs(os.path.dirname(_UNBOUND_CONF_PATH), exist_ok=True)
    try:
        with open(_UNBOUND_CONF_PATH, "w") as fh:
            fh.write(conf)
        return {"ok": True, "message": f"Written to {_UNBOUND_CONF_PATH}", "conf": conf}
    except OSError as exc:
        return {"ok": False, "message": str(exc), "conf": conf}
