"""
ids_writer.py
-------------
Generates Suricata YAML configuration from Smart Shield's ids_config /
ids_rulesets tables and manages the suricata service on FreeBSD.

FreeBSD package:  pkg install suricata
Service name:     suricata
Config path:      /usr/local/etc/suricata/suricata.yaml
Rules dir:        /usr/local/etc/suricata/rules/
Logs:             /var/log/suricata/

Public API
----------
generate_suricata_yaml(conn)     -> str
write_suricata_config(conn)      -> {"ok", "message", "conf"}
update_rules(conn)               -> {"ok", "message", "updated": [...]}
get_ids_status()                 -> {"ok", "running", "mode", "message", "alerts_today"}
toggle_ids(conn, enabled: bool)  -> {"ok", "message"}
"""

import json
import os
import sys
import textwrap

from app.services.network_service import run_command, FreeBSDNetworkError
from app.services.service_manager import service_action, sysrc_set

_SURICATA_CONF_DIR  = "/usr/local/etc/suricata"
_SURICATA_CONF_PATH = "/usr/local/etc/suricata/suricata.yaml"
_SURICATA_RULES_DIR = "/usr/local/etc/suricata/rules"
_SURICATA_LOG_DIR   = "/var/log/suricata"
_SURICATA_RUN_DIR   = "/var/run/suricata"
_SERVICE_NAME       = "suricata"


def _rows(conn, sql, params=()):
    cur = conn.cursor()
    cur.execute(sql, params)
    return [dict(r) for r in cur.fetchall()]


def _cfg(conn) -> dict:
    rows = _rows(conn, "SELECT * FROM ids_config WHERE id=1")
    return rows[0] if rows else {}


# ---------------------------------------------------------------------------
# YAML generator
# ---------------------------------------------------------------------------

def generate_suricata_yaml(conn) -> str:
    cfg = _cfg(conn)
    if not cfg:
        cfg = {}

    mode        = cfg.get("mode", "ids")
    interface   = cfg.get("interface") or "em0"
    home_net    = cfg.get("home_net") or "192.168.0.0/16"
    ext_net     = cfg.get("external_net") or "!$HOME_NET"
    eve_enabled = bool(cfg.get("eve_json_enabled", 1))
    fast_log    = bool(cfg.get("fast_log_enabled", 1))
    max_pending = int(cfg.get("max_pending_packets") or 1024)
    stats_int   = int(cfg.get("stats_interval") or 8)

    # Active rulesets
    rulesets = _rows(conn, "SELECT * FROM ids_rulesets WHERE enabled=1 ORDER BY id")
    rule_files = []
    for rs in rulesets:
        lp = (rs.get("local_path") or "").strip()
        nm = (rs.get("name") or "ruleset").strip().lower().replace(" ", "_")
        path = lp if lp else f"{_SURICATA_RULES_DIR}/{nm}.rules"
        rule_files.append(path)

    if not rule_files:
        rule_files = [f"{_SURICATA_RULES_DIR}/emerging-threats.rules"]

    # Build capture config depending on mode
    if mode == "ips":
        capture_section = textwrap.dedent(f"""\
            netmap:
              - interface: {interface}
                threads: auto
                copy-mode: ips
                copy-iface: {interface}
        """)
        runmode = "workers"
    else:
        capture_section = textwrap.dedent(f"""\
            af-packet:
              - interface: {interface}
                threads: auto
                cluster-id: 99
                cluster-type: cluster_flow
                defrag: yes
        """)
        runmode = "autofp"

    # EVE log outputs
    outputs_list = []
    if eve_enabled:
        outputs_list.append(textwrap.dedent("""\
            - eve-log:
                enabled: yes
                filetype: regular
                filename: /var/log/suricata/eve.json
                types:
                  - alert:
                      payload: yes
                      metadata: yes
                  - dns
                  - http:
                      extended: yes
                  - tls:
                      extended: yes
                  - files
                  - stats:
                      totals: yes
        """))
    if fast_log:
        outputs_list.append(textwrap.dedent("""\
            - fast:
                enabled: yes
                filename: /var/log/suricata/fast.log
                append: yes
        """))
    outputs_list.append(textwrap.dedent("""\
        - stats:
            enabled: yes
            filename: /var/log/suricata/stats.log
            append: yes
            totals: yes
            threads: no
    """))

    outputs_yaml = "\n".join(outputs_list)

    rule_files_yaml = "\n".join(f"  - {p}" for p in rule_files)

    yaml = textwrap.dedent(f"""\
        %YAML 1.1
        ---
        # ============================================================
        # Smart Shield — auto-generated suricata.yaml
        # Generated by app/services/ids_writer.py
        # Mode: {mode.upper()}  Interface: {interface}
        # ============================================================

        vars:
          address-groups:
            HOME_NET: "[{home_net}]"
            EXTERNAL_NET: "{ext_net}"
            HTTP_SERVERS: "$HOME_NET"
            SMTP_SERVERS: "$HOME_NET"
            SQL_SERVERS: "$HOME_NET"
            DNS_SERVERS: "$HOME_NET"
            TELNET_SERVERS: "$HOME_NET"
            AIM_SERVERS: "$EXTERNAL_NET"
            DC_SERVERS: "$HOME_NET"
            DNP3_SERVER: "$HOME_NET"
            DNP3_CLIENT: "$HOME_NET"
            MODBUS_CLIENT: "$HOME_NET"
            MODBUS_SERVER: "$HOME_NET"
            ENIP_CLIENT: "$HOME_NET"
            ENIP_SERVER: "$HOME_NET"

          port-groups:
            HTTP_PORTS: "80"
            SHELLCODE_PORTS: "!80"
            ORACLE_PORTS: 1521
            SSH_PORTS: 22
            DNP3_PORTS: 20000
            MODBUS_PORTS: 502
            FILE_DATA_PORTS: "[$HTTP_PORTS,110,143]"
            FTP_PORTS: 21
            GENEVE_PORTS: 6081
            VXLAN_PORTS: 4789
            TEREDO_PORTS: 3544

        default-log-dir: {_SURICATA_LOG_DIR}

        stats:
          enabled: yes
          interval: {stats_int}

        outputs:
        {outputs_yaml}

        af-packet:
          - interface: default

        {capture_section}

        app-layer:
          protocols:
            rdp:
              enabled: yes
            krb5:
              enabled: yes
            snmp:
              enabled: yes
            ikev2:
              enabled: yes
            tls:
              enabled: yes
              detection-ports:
                dp: 443
            http2:
              enabled: yes
            smtp:
              enabled: yes
            imap:
              enabled: yes
            ssh:
              enabled: yes
            ftp:
              enabled: yes
            dns:
              tcp:
                enabled: yes
              udp:
                enabled: yes
            http:
              enabled: yes
              libhtp:
                default-config:
                  personality: IDS
                  request-body-limit: 100kb
                  response-body-limit: 100kb
                  double-decode-path: no
                  double-decode-query: no

        threading:
          set-cpu-affinity: no
          cpu-affinity:
            - management-cpu-set:
                cpu: [ 0 ]
            - receive-cpu-set:
                cpu: [ 0 ]
            - worker-cpu-set:
                cpu: [ "all" ]
                mode: "exclusive"
                prio:
                  low: [ 0 ]
                  medium: [ "1-2" ]
                  high: [ 3 ]
                  default: "medium"
          detect-thread-ratio: 1.0

        detect:
          profile: medium
          custom-values:
            toclient-groups: 3
            toserver-groups: 25
          sgh-mpm-context: auto
          inspection-recursion-limit: 3000
          prefilter:
            default: mpm
          grouping:
          profiling:
            grouping:
              dump-to-disk: false

        mpm-algo: auto
        spm-algo: auto

        runmode: {runmode}

        max-pending-packets: {max_pending}

        default-packet-size: 1514

        host-mode: auto

        home-net-ranges:
          - {home_net}

        defrag:
          memcap: 32mb
          hash-size: 65536
          trackers: 65535
          max-frags: 65535
          prealloc: yes
          timeout: 60

        flow:
          memcap: 128mb
          hash-size: 65536
          prealloc: 10000
          emergency-recovery: 30

        vlan:
          use-for-tracking: true

        stream:
          memcap: 64mb
          checksum-validation: yes
          inline: {str(mode == 'ips').lower()}
          reassembly:
            memcap: 256mb
            depth: 1mb
            toserver-chunk-size: 2560
            toclient-chunk-size: 2560
            randomize-chunk-size: yes

        host:
          hash-size: 4096
          prealloc: 1000
          memcap: 32mb

        rule-files:
        {rule_files_yaml}

        classification-file: {_SURICATA_CONF_DIR}/classification.config
        reference-config-file: {_SURICATA_CONF_DIR}/reference.config

        suppress-version-message: yes
    """)
    return yaml


# ---------------------------------------------------------------------------
# Write config
# ---------------------------------------------------------------------------

def write_suricata_config(conn) -> dict:
    conf = generate_suricata_yaml(conn)

    if not sys.platform.startswith("freebsd"):
        return {"ok": True, "message": "Non-FreeBSD — suricata.yaml generated but not written.", "conf": conf}

    os.makedirs(_SURICATA_CONF_DIR, exist_ok=True)
    os.makedirs(_SURICATA_LOG_DIR, exist_ok=True)
    os.makedirs(_SURICATA_RUN_DIR, exist_ok=True)
    os.makedirs(_SURICATA_RULES_DIR, exist_ok=True)

    try:
        with open(_SURICATA_CONF_PATH, "w") as fh:
            fh.write(conf)
        return {"ok": True, "message": f"Written to {_SURICATA_CONF_PATH}", "conf": conf}
    except OSError as exc:
        return {"ok": False, "message": str(exc), "conf": conf}


# ---------------------------------------------------------------------------
# Rule updates via suricata-update
# ---------------------------------------------------------------------------

def update_rules(conn) -> dict:
    """
    Run `suricata-update` to download/update all enabled rulesets.
    Returns per-ruleset results.
    """
    if not sys.platform.startswith("freebsd"):
        return {"ok": True, "message": "Non-FreeBSD — rule update skipped.", "updated": []}

    rulesets = _rows(conn, "SELECT * FROM ids_rulesets WHERE enabled=1")
    updated = []
    errors  = []

    for rs in rulesets:
        url = (rs.get("url") or "").strip()
        name = rs.get("name", "")
        if not url:
            continue
        try:
            result = run_command(["suricata-update", "add-source", name, url], check=False)
            updated.append({"name": name, "ok": result.returncode == 0})
        except FreeBSDNetworkError as exc:
            errors.append(f"{name}: {exc}")

    # Run the actual update
    try:
        result = run_command(["suricata-update"], check=False)
        ok = result.returncode == 0
    except FreeBSDNetworkError as exc:
        return {"ok": False, "message": str(exc), "updated": updated}

    return {
        "ok": ok,
        "message": "Rule update completed." if ok else "Rule update had errors — check logs.",
        "updated": updated,
    }


# ---------------------------------------------------------------------------
# Status
# ---------------------------------------------------------------------------

def get_ids_status() -> dict:
    """Return running status + today's alert count (from eve.json)."""
    if not sys.platform.startswith("freebsd"):
        return {"ok": True, "running": False, "mode": "ids", "message": "Non-FreeBSD host", "alerts_today": 0}

    # Check if process is running
    result = run_command(["pgrep", "-x", "suricata"], check=False)
    running = result.returncode == 0

    alerts_today = 0
    eve_path = f"{_SURICATA_LOG_DIR}/eve.json"
    if os.path.exists(eve_path):
        try:
            from datetime import datetime, timezone
            today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
            with open(eve_path, "r", errors="replace") as f:
                for line in f:
                    if '"event_type":"alert"' in line and today in line:
                        alerts_today += 1
        except Exception:
            pass

    return {
        "ok": True,
        "running": running,
        "mode": "ids",
        "message": "Running" if running else "Stopped",
        "alerts_today": alerts_today,
    }


# ---------------------------------------------------------------------------
# Enable / disable
# ---------------------------------------------------------------------------

def toggle_ids(conn, enabled: bool) -> dict:
    """Enable or disable Suricata, writing config first if enabling."""
    # Update DB
    cur = conn.cursor()
    cur.execute("UPDATE ids_config SET enabled=?, updated_at=CURRENT_TIMESTAMP WHERE id=1", (1 if enabled else 0,))
    conn.commit()

    if not sys.platform.startswith("freebsd"):
        return {"ok": True, "message": f"IDS {'enabled' if enabled else 'disabled'} (non-FreeBSD, not applied)"}

    if enabled:
        write_result = write_suricata_config(conn)
        if not write_result["ok"]:
            return write_result
        sysrc_set("suricata_enable", "YES")
        return service_action(_SERVICE_NAME, "restart")
    else:
        sysrc_set("suricata_enable", "NO")
        return service_action(_SERVICE_NAME, "stop")
