"""
ipsec_writer.py
---------------
Generates strongSwan ipsec.conf + ipsec.secrets from Smart Shield's
ipsec_phase1 / ipsec_phase2 / ipsec_pre_shared_keys tables.

Public API
----------
generate_ipsec_conf(conn)    -> str
generate_ipsec_secrets(conn) -> str
write_ipsec_conf(conn)       -> {"ok": bool, "message": str}
"""

import ipaddress
import os
import sys

from app.secret_store import decrypt_secret

# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

_VALID_IKE_VERSIONS = {"ikev1", "ikev2", "ike"}
_VALID_ENCS         = {"aes", "aes128", "aes192", "aes256", "3des", "camellia128", "camellia256"}
_VALID_HASH_ALGS    = {"sha1", "sha256", "sha384", "sha512", "md5", "aesxcbc"}
_VALID_DH_GROUPS    = {
    # Numeric shorthand used in the UI
    "1", "2", "5", "14", "15", "16", "17", "18", "19", "20", "21",
    # Full names as used in strongSwan proposals
    "modp768", "modp1024", "modp2048", "modp4096", "modp8192",
    "ecp256", "ecp384", "ecp521", "curve25519",
    # 1024, 2048, 4096 numeric strings (stored without "modp" prefix in some rows)
    "1024", "2048", "4096", "8192",
}


def validate_phase1(p1: dict, algs: list) -> list:
    """
    Validate a Phase 1 configuration dict.
    Returns a list of error strings; empty means valid.
    """
    errors = []

    ike_ver = (p1.get("ike_version") or "ikev2").lower()
    if ike_ver not in _VALID_IKE_VERSIONS:
        errors.append(f"IKE version {ike_ver!r} is not supported. Use ikev1 or ikev2.")

    remote = (p1.get("remote_gateway") or "").strip()
    if not remote:
        errors.append("Remote gateway is required.")
    else:
        try:
            ipaddress.ip_address(remote)
        except ValueError:
            # Accept hostnames too — just verify it's not empty or obviously wrong
            if " " in remote or len(remote) > 253:
                errors.append(f"Remote gateway {remote!r} does not look like a valid IP or hostname.")

    lifetime = p1.get("p1_life_time") or 28800
    try:
        lt = int(lifetime)
        if lt < 300:
            errors.append(f"Phase 1 lifetime {lt}s is very short (minimum recommended: 300s).")
    except (TypeError, ValueError):
        errors.append(f"Phase 1 lifetime {lifetime!r} must be an integer.")

    if not algs:
        errors.append("At least one Phase 1 algorithm must be configured.")
    for alg in algs:
        enc = (alg.get("encryption") or "").lower()
        hsh = (alg.get("hash") or "").lower()
        dh  = str(alg.get("dh_group") or "").lower().replace("modp", "")
        if enc and enc not in _VALID_ENCS:
            errors.append(f"Unknown encryption algorithm: {enc!r}.")
        if hsh and hsh not in _VALID_HASH_ALGS:
            errors.append(f"Unknown hash algorithm: {hsh!r}.")
        if dh and dh not in _VALID_DH_GROUPS:
            errors.append(f"Unknown DH group: {dh!r}.")

    auth = (p1.get("auth_method") or "mutual-psk").lower()
    if "psk" in auth:
        psk_raw = (p1.get("pre_shared_key") or "").strip()
        if psk_raw:
            from app.secret_store import decrypt_secret as _ds
            if not _ds(psk_raw):
                errors.append("PSK is stored but cannot be decrypted — re-enter the PSK.")
        else:
            errors.append("PSK authentication selected but no pre-shared key configured.")

    return errors


def validate_phase2(p2: dict) -> list:
    """
    Validate a Phase 2 (child SA) configuration dict.
    Returns a list of error strings; empty means valid.
    """
    errors = []

    local_net = (p2.get("local_network") or "").strip()
    remote_net = (p2.get("remote_network") or "").strip()
    for label, net in [("Local network", local_net), ("Remote network", remote_net)]:
        if net and net != "0.0.0.0/0":
            try:
                ipaddress.ip_network(net, strict=False)
            except ValueError:
                errors.append(f"{label} {net!r} is not a valid CIDR.")

    lifetime = p2.get("lifetime") or 3600
    try:
        lt = int(lifetime)
        if lt < 60:
            errors.append(f"Phase 2 lifetime {lt}s is too short (minimum: 60s).")
    except (TypeError, ValueError):
        errors.append(f"Phase 2 lifetime {lifetime!r} must be an integer.")

    return errors

_IPSEC_CONF_PATH    = "/usr/local/etc/ipsec.conf"
_IPSEC_SECRETS_PATH = "/usr/local/etc/ipsec.secrets"


def _rows(conn, sql, params=()):
    cur = conn.cursor()
    cur.execute(sql, params)
    return [dict(r) for r in cur.fetchall()]


def _val(row, key, default=""):
    return (row.get(key) or default)


def generate_ipsec_conf(conn) -> str:
    lines = [
        "# ============================================================",
        "# Smart Shield — auto-generated ipsec.conf (strongSwan)",
        "# Generated by app/services/ipsec_writer.py",
        "# DO NOT EDIT MANUALLY",
        "# ============================================================",
        "",
        "config setup",
        '    charondebug="ike 1, knl 1, cfg 0, net 1"',
        "    uniqueids=no",
        "",
    ]

    phase1s = _rows(conn, "SELECT * FROM ipsec_phase1 WHERE disabled=0 ORDER BY id")
    for p1 in phase1s:
        p1id      = p1["id"]
        conn_name = f"tunnel_{p1id}"
        remote    = _val(p1, "remote_gateway")
        ike_ver   = _val(p1, "ike_version", "ikev2")
        auth_meth = _val(p1, "auth_method", "mutual-psk")
        left_id   = _val(p1, "my_identifier", "%defaultroute")
        right_id  = _val(p1, "peer_identifier", "%any")
        lifetime  = _val(p1, "p1_life_time", "28800")
        dpd_en    = bool(p1.get("dpd_enable", 1))
        dpd_delay = p1.get("dpd_delay") or 10
        dpd_fail  = p1.get("dpd_max_failures") or 5
        nat_trav  = _val(p1, "nat_traversal", "auto")
        desc      = _val(p1, "description")

        # Map auth_method → strongSwan leftauth/rightauth
        if "psk" in auth_meth:
            left_auth, right_auth = "psk", "psk"
        elif "cert" in auth_meth or "rsa" in auth_meth:
            left_auth, right_auth = "pubkey", "pubkey"
        elif "xauth" in auth_meth:
            left_auth, right_auth = "psk", "xauth"
        else:
            left_auth, right_auth = "psk", "psk"

        left_id_str  = "%defaultroute" if left_id  in ("my-ip","myaddress","%defaultroute","") else left_id
        right_id_str = "%any"          if right_id in ("peer-ip","any","%any","")              else right_id

        # Pull algorithms for this phase1
        algs = _rows(conn, """
            SELECT encryption, key_length, hash, dh_group
            FROM ipsec_phase1_algorithms WHERE phase1_id=? ORDER BY id
        """, (p1id,))

        ike_proposals = []
        for alg in algs:
            enc = _val(alg, "encryption", "aes256")
            kl  = alg.get("key_length") or ""
            hsh = _val(alg, "hash", "sha256")
            dh  = _val(alg, "dh_group", "modp2048")
            enc_str = f"{enc}{kl}" if kl else enc
            ike_proposals.append(f"{enc_str}-{hsh}-{dh}")

        ike_str = ",".join(ike_proposals) if ike_proposals else "aes256-sha256-modp2048"

        # Phase 2 child SAs
        phase2s = _rows(conn, """
            SELECT * FROM ipsec_phase2 WHERE phase1_id=? AND disabled=0 ORDER BY id
        """, (p1id,))

        if desc:
            lines.append(f"# {desc}")
        lines += [
            f"conn {conn_name}",
            f"    keyexchange={ike_ver}",
            f"    left=%defaultroute",
            f"    leftid={left_id_str}",
            f"    leftauth={left_auth}",
            f"    right={remote}",
            f"    rightid={right_id_str}",
            f"    rightauth={right_auth}",
            f"    ike={ike_str}!",
            f"    ikelifetime={lifetime}s",
            "    keyingtries=3",
            "    auto=start",
        ]

        if nat_trav == "force":
            lines.append("    forceencaps=yes")
        elif nat_trav == "disable":
            lines.append("    forceencaps=no")

        if dpd_en:
            lines += [
                f"    dpddelay={dpd_delay}s",
                f"    dpdtimeout={dpd_delay * dpd_fail}s",
                "    dpdaction=restart",
            ]

        if phase2s:
            p2          = phase2s[0]
            local_net   = _val(p2, "local_network",  "0.0.0.0/0")
            remote_net  = _val(p2, "remote_network", "0.0.0.0/0")
            p2_lifetime = p2.get("lifetime") or 3600
            enc_algs    = _val(p2, "encryption_algorithms", "aes256")
            hash_algs   = _val(p2, "hash_algorithms", "sha256")
            pfs_group   = _val(p2, "pfs_key_group", "14")
            esp_str     = (f"{enc_algs}-{hash_algs}-modp{pfs_group}!"
                           if pfs_group and pfs_group != "0"
                           else f"{enc_algs}-{hash_algs}!")
            lines += [
                f"    leftsubnet={local_net}",
                f"    rightsubnet={remote_net}",
                f"    esp={esp_str}",
                f"    lifetime={p2_lifetime}s",
            ]

        lines.append("")

    return "\n".join(lines)


def generate_ipsec_secrets(conn) -> str:
    lines = [
        "# ============================================================",
        "# Smart Shield — auto-generated ipsec.secrets",
        "# Generated by app/services/ipsec_writer.py",
        "# ============================================================",
        "",
    ]

    seen = set()

    # 1. Inline PSKs stored per phase1 tunnel (auth_method contains 'psk')
    phase1s = _rows(conn, """
        SELECT remote_gateway, pre_shared_key, my_identifier, peer_identifier
        FROM ipsec_phase1
        WHERE disabled=0 AND pre_shared_key != '' AND pre_shared_key IS NOT NULL
    """)
    for p1 in phase1s:
        left  = (p1.get("my_identifier") or "%any").strip()
        right = (p1.get("remote_gateway") or "%any").strip()
        psk   = decrypt_secret((p1.get("pre_shared_key") or "").strip())
        if not psk:
            continue
        left_str  = "%any" if left  in ("my-ip","myaddress","%defaultroute","") else left
        right_str = right or "%any"
        key = (left_str, right_str)
        if key not in seen:
            seen.add(key)
            lines.append(f"{left_str} {right_str} : PSK \"{psk}\"")

    # 2. Dedicated PSK table entries
    psks = _rows(conn, "SELECT * FROM ipsec_pre_shared_keys ORDER BY id")
    for psk in psks:
        identifier = (psk.get("identifier") or "%any").strip()
        secret     = decrypt_secret((psk.get("pre_shared_key") or "").strip())
        if not secret:
            continue
        key = (identifier, "")
        if key not in seen:
            seen.add(key)
            lines.append(f"{identifier} : PSK \"{secret}\"")

    lines.append("")
    return "\n".join(lines)


def write_ipsec_conf(conn) -> dict:
    conf    = generate_ipsec_conf(conn)
    secrets = generate_ipsec_secrets(conn)

    if not sys.platform.startswith("freebsd"):
        return {
            "ok": True,
            "message": "Non-FreeBSD — ipsec.conf generated but not written.",
            "conf": conf,
            "secrets": secrets,
        }

    errors = []
    for path, content in [(_IPSEC_CONF_PATH, conf), (_IPSEC_SECRETS_PATH, secrets)]:
        try:
            with open(path, "w") as fh:
                fh.write(content)
            if path.endswith("secrets"):
                os.chmod(path, 0o600)
        except OSError as exc:
            errors.append(f"{path}: {exc}")

    if errors:
        return {"ok": False, "message": "; ".join(errors), "conf": conf}
    return {"ok": True, "message": "ipsec.conf + ipsec.secrets written.", "conf": conf}


def validate_ipsec_config(conn) -> list:
    """
    Validate all enabled Phase 1 + Phase 2 entries.
    Returns a list of error strings; empty means valid.
    """
    all_errors = []
    phase1s = _rows(conn, "SELECT * FROM ipsec_phase1 WHERE disabled=0 ORDER BY id")
    for p1 in phase1s:
        p1id = p1["id"]
        algs = _rows(conn, "SELECT * FROM ipsec_phase1_algorithms WHERE phase1_id=?", (p1id,))
        errs = validate_phase1(p1, algs)
        if errs:
            desc = p1.get("description") or f"tunnel {p1id}"
            all_errors.extend(f"[{desc}] {e}" for e in errs)

        phase2s = _rows(conn, "SELECT * FROM ipsec_phase2 WHERE phase1_id=? AND disabled=0", (p1id,))
        for p2 in phase2s:
            errs2 = validate_phase2(p2)
            if errs2:
                desc2 = p2.get("description") or f"child-SA {p2['id']}"
                all_errors.extend(f"[{desc2}] {e}" for e in errs2)
    return all_errors


def apply_ipsec(conn) -> dict:
    """Validate, write config files, then reload strongSwan."""
    validation_errors = validate_ipsec_config(conn)
    if validation_errors:
        return {
            "ok": False,
            "message": "Validation failed: " + " | ".join(validation_errors),
        }

    result = write_ipsec_conf(conn)
    if not result["ok"] or not sys.platform.startswith("freebsd"):
        return result
    try:
        from app.services.network_service import run_command
        # Try 'ipsec reload' first; fall back to full restart
        r = run_command(["ipsec", "reload"], check=False)
        if r.returncode != 0:
            r = run_command(["service", "strongswan", "restart"], check=False)
        ok = r.returncode == 0
        return {"ok": ok,
                "message": result["message"] + " | ipsec reload: " + (r.stdout or r.stderr or "").strip()}
    except Exception as exc:
        return {"ok": False, "message": f"Config written but reload failed: {exc}"}


def get_ipsec_status() -> dict:
    """Return running tunnel status from 'ipsec statusall'."""
    if not sys.platform.startswith("freebsd"):
        return {"running": False, "tunnels": [], "message": "Not on FreeBSD"}
    try:
        from app.services.network_service import run_command
        r = run_command(["ipsec", "statusall"], check=False)
        output = (r.stdout or "").strip()
        tunnels = []
        for line in output.splitlines():
            if "ESTABLISHED" in line or "INSTALLED" in line:
                tunnels.append(line.strip())
        return {
            "running": r.returncode == 0,
            "tunnels": tunnels,
            "raw": output[:4000],
        }
    except Exception as exc:
        return {"running": False, "tunnels": [], "message": str(exc)}
