"""
ipsec_writer.py
---------------
Generates strongSwan ipsec.conf + ipsec.secrets from Smart Shield's
ipsec_phase1 / ipsec_phase2 / ipsec_pre_shared_keys tables.

Public API
----------
generate_ipsec_conf(conn)    -> str
generate_ipsec_secrets(conn) -> str
write_ipsec_conf(conn)       -> {"ok": bool, "message": str}
"""

import os
import sys

_IPSEC_CONF_PATH    = "/usr/local/etc/ipsec.conf"
_IPSEC_SECRETS_PATH = "/usr/local/etc/ipsec.secrets"


def _rows(conn, sql, params=()):
    cur = conn.cursor()
    cur.execute(sql, params)
    return [dict(r) for r in cur.fetchall()]


def _val(row, key, default=""):
    return (row.get(key) or default)


def generate_ipsec_conf(conn) -> str:
    lines = [
        "# ============================================================",
        "# Smart Shield — auto-generated ipsec.conf (strongSwan)",
        "# Generated by app/services/ipsec_writer.py",
        "# DO NOT EDIT MANUALLY",
        "# ============================================================",
        "",
        "config setup",
        "    charondebug=\"ike 1, knl 1, cfg 0\"",
        "    uniqueids=no",
        "",
    ]

    phase1s = _rows(conn, "SELECT * FROM ipsec_phase1 WHERE disabled=0 ORDER BY id")
    for p1 in phase1s:
        p1id    = p1["id"]
        conn_name = f"tunnel_{p1id}"
        remote  = _val(p1, "remote_gateway")
        ike_ver = _val(p1, "ike_version", "ikev2")
        left_id = _val(p1, "my_identifier", "%defaultroute")
        right_id = _val(p1, "peer_identifier", "%any")
        lifetime = _val(p1, "p1_life_time", "28800")
        desc = _val(p1, "description")

        # Pull algorithms for this phase1
        algs = _rows(conn, """
            SELECT encryption, key_length, hash, dh_group
            FROM ipsec_phase1_algorithms WHERE phase1_id=? ORDER BY id
        """, (p1id,))

        ike_proposals = []
        for alg in algs:
            enc = _val(alg, "encryption", "aes256")
            kl  = alg.get("key_length") or ""
            hsh = _val(alg, "hash", "sha256")
            dh  = _val(alg, "dh_group", "modp2048")
            enc_str = f"{enc}{kl}" if kl else enc
            ike_proposals.append(f"{enc_str}-{hsh}-{dh}")

        ike_str = ",".join(ike_proposals) if ike_proposals else "aes256-sha256-modp2048"

        # Phase 2 entries for this tunnel
        phase2s = _rows(conn, """
            SELECT * FROM ipsec_phase2 WHERE phase1_id=? AND disabled=0 ORDER BY id
        """, (p1id,))

        if desc:
            lines.append(f"# {desc}")
        lines += [
            f"conn {conn_name}",
            f"    keyexchange={ike_ver}",
            f"    left=%defaultroute",
            f"    leftid={left_id}",
            f"    right={remote}",
            f"    rightid={right_id}",
            f"    ike={ike_str}!",
            f"    ikelifetime={lifetime}s",
            "    auto=start",
        ]

        if phase2s:
            p2 = phase2s[0]
            local_net   = _val(p2, "local_network",  "0.0.0.0/0")
            remote_net  = _val(p2, "remote_network", "0.0.0.0/0")
            p2_lifetime = _val(p2, "lifetime", "3600")
            proto_esp   = _val(p2, "protocol", "esp").lower()
            enc_algs    = _val(p2, "encryption_algorithms", "aes256")
            hash_algs   = _val(p2, "hash_algorithms", "sha256")
            pfs_group   = _val(p2, "pfs_key_group", "14")
            esp_str = f"{enc_algs}-{hash_algs}-modp{pfs_group}!" if pfs_group != "0" else f"{enc_algs}-{hash_algs}!"
            lines += [
                f"    leftsubnet={local_net}",
                f"    rightsubnet={remote_net}",
                f"    esp={esp_str}",
                f"    lifetime={p2_lifetime}s",
            ]

        lines.append("")

    return "\n".join(lines)


def generate_ipsec_secrets(conn) -> str:
    lines = [
        "# ============================================================",
        "# Smart Shield — auto-generated ipsec.secrets",
        "# Generated by app/services/ipsec_writer.py",
        "# ============================================================",
        "",
    ]

    psks = _rows(conn, "SELECT * FROM ipsec_pre_shared_keys ORDER BY id")
    for psk in psks:
        identifier = (psk.get("identifier") or "%any").strip()
        secret = (psk.get("pre_shared_key") or "").strip()
        if not secret:
            continue
        lines.append(f"{identifier} : PSK \"{secret}\"")

    lines.append("")
    return "\n".join(lines)


def write_ipsec_conf(conn) -> dict:
    conf    = generate_ipsec_conf(conn)
    secrets = generate_ipsec_secrets(conn)

    if not sys.platform.startswith("freebsd"):
        return {
            "ok": True,
            "message": "Non-FreeBSD — ipsec.conf generated but not written.",
            "conf": conf,
            "secrets": secrets,
        }

    errors = []
    for path, content in [(_IPSEC_CONF_PATH, conf), (_IPSEC_SECRETS_PATH, secrets)]:
        try:
            with open(path, "w") as fh:
                fh.write(content)
            if path.endswith("secrets"):
                os.chmod(path, 0o600)
        except OSError as exc:
            errors.append(f"{path}: {exc}")

    if errors:
        return {"ok": False, "message": "; ".join(errors), "conf": conf}
    return {"ok": True, "message": "ipsec.conf + ipsec.secrets written.", "conf": conf}
