"""
l2tp_writer.py
--------------
Generates mpd5 (Multi-link PPP daemon) configuration for L2TP/IPsec on FreeBSD.
Files written:
  /usr/local/etc/mpd5/mpd.conf  — main config
  /usr/local/etc/mpd5/mpd.secret— user credentials

Public API
----------
generate_mpd_conf(conn)    -> str
generate_mpd_secret(conn)  -> str
write_l2tp_conf(conn)      -> {"ok": bool, "message": str}
apply_l2tp(conn)           -> {"ok": bool, "message": str}
get_l2tp_status()          -> {"running": bool, "sessions": [...]}
"""
import os
import sys

_MPD_DIR    = "/usr/local/etc/mpd5"
_MPD_CONF   = "/usr/local/etc/mpd5/mpd.conf"
_MPD_SECRET = "/usr/local/etc/mpd5/mpd.secret"


def _rows(conn, sql, params=()):
    cur = conn.cursor()
    cur.execute(sql, params)
    return [dict(r) for r in cur.fetchall()]


def _on_freebsd():
    return sys.platform.startswith("freebsd")


def _v(row, key, default=""):
    return row.get(key) or default


def generate_mpd_conf(conn) -> str:
    cfg_rows = _rows(conn, "SELECT * FROM l2tp_config WHERE id=1 LIMIT 1")
    cfg = cfg_rows[0] if cfg_rows else {}

    server_addr   = _v(cfg, "server_address",     "192.168.1.1")
    remote_range  = _v(cfg, "remote_address_range","192.168.1.200")
    subnet_mask   = _v(cfg, "subnet_mask",         "255.255.255.0")
    auth_type     = _v(cfg, "authentication",      "chap").upper()
    dns1          = _v(cfg, "dns_server1",         "")
    dns2          = _v(cfg, "dns_server2",         "")

    # Derive pool range: assume /24, give 50 addresses from remote_range
    pool_start = remote_range
    try:
        import ipaddress
        base = ipaddress.ip_address(remote_range)
        pool_end = str(base + 49)
    except Exception:
        pool_end = remote_range

    lines = [
        "#",
        "# mpd5 L2TP/IPsec configuration",
        "# Auto-generated by Smart Shield — DO NOT EDIT MANUALLY",
        "#",
        "",
        "startup:",
        '    load l2tp_server',
        "",
        "l2tp_server:",
        "    set ippool add pool1 " + pool_start + " " + pool_end,
        "",
        "    create bundle template B_L2TP",
        "    set iface enable proxy-arp",
        "    set iface enable tcpmssfix",
        f"    set ipcp ranges {server_addr}/32 ippool pool1",
    ]

    if dns1:
        lines.append(f"    set ipcp dns {dns1}")
    if dns2:
        lines.append(f"    set ipcp dns {dns2}")

    lines += [
        "",
        "    set bundle enable multilink",
        "    set bundle enable shortseq",
        "    set link yes acfcomp protocomp",
        "    set link no pap",
        "    set link enable " + ("mschapv2" if "CHAP" in auth_type else "pap"),
        f'    set auth authname "l2tpd"',
        "    set link keep-alive 10 60",
        "    set link max-redial 0",
        "",
        "    create link template L_L2TP l2tp",
        "    set l2tp enable incoming",
        "    set l2tp disable originate",
        "    set l2tp enable length",
        f'    set l2tp self {server_addr}',
        "    set link action bundle B_L2TP",
        "",
    ]

    return "\n".join(lines)


def generate_mpd_secret(conn) -> str:
    users = _rows(conn, "SELECT username, password, ip_address FROM l2tp_users ORDER BY id")
    lines = [
        "# mpd5 secret file — auto-generated by Smart Shield",
        "# format: username password [ip-address]",
        "",
    ]
    for u in users:
        username = (u.get("username") or "").strip()
        password = (u.get("password") or "").strip()
        ip_addr  = (u.get("ip_address") or "").strip()
        if not username or not password:
            continue
        if ip_addr:
            lines.append(f'"{username}" "{password}" {ip_addr}')
        else:
            lines.append(f'"{username}" "{password}"')
    lines.append("")
    return "\n".join(lines)


def write_l2tp_conf(conn) -> dict:
    conf   = generate_mpd_conf(conn)
    secret = generate_mpd_secret(conn)

    if not _on_freebsd():
        return {
            "ok": True,
            "message": "Non-FreeBSD — mpd5 config generated but not written.",
            "conf": conf,
        }

    os.makedirs(_MPD_DIR, exist_ok=True)
    errors = []
    for path, content, mode in [
        (_MPD_CONF,   conf,   0o644),
        (_MPD_SECRET, secret, 0o600),
    ]:
        try:
            with open(path, "w") as fh:
                fh.write(content)
            os.chmod(path, mode)
        except OSError as exc:
            errors.append(f"{path}: {exc}")

    if errors:
        return {"ok": False, "message": "; ".join(errors)}
    return {"ok": True, "message": f"mpd.conf + mpd.secret written to {_MPD_DIR}"}


def apply_l2tp(conn) -> dict:
    result = write_l2tp_conf(conn)
    if not result["ok"] or not _on_freebsd():
        return result
    try:
        from app.services.service_manager import service_action
        r = service_action("mpd5", "restart")
        return {
            "ok": r["ok"],
            "message": result["message"] + " | Service: " + r["message"],
        }
    except Exception as exc:
        return {"ok": False, "message": f"Config written but restart failed: {exc}"}


def get_l2tp_status() -> dict:
    if not _on_freebsd():
        return {"running": False, "sessions": [], "message": "Not on FreeBSD"}
    try:
        from app.services.network_service import run_command
        # Ask mpd5 via telnet control interface (port 5006 default)
        r = run_command(["pgrep", "-a", "mpd5"], check=False)
        lines = [l.strip() for l in (r.stdout or "").splitlines() if l.strip()]
        running = bool(lines)

        sessions = []
        if running:
            # Try to get active sessions via netstat
            ns = run_command(["netstat", "-na", "-p", "udp"], check=False)
            for line in (ns.stdout or "").splitlines():
                if "l2tp" in line.lower() or ":1701" in line:
                    sessions.append(line.strip())

        return {"running": running, "sessions": sessions}
    except Exception as exc:
        return {"running": False, "sessions": [], "message": str(exc)}
