"""
l2tp_writer.py
--------------
Generates mpd5 (Multi-link PPP daemon) configuration for L2TP/IPsec on FreeBSD.
Files written:
  /usr/local/etc/mpd5/mpd.conf  — main config
  /usr/local/etc/mpd5/mpd.secret— user credentials

Public API
----------
generate_mpd_conf(conn)    -> str
generate_mpd_secret(conn)  -> str
write_l2tp_conf(conn)      -> {"ok": bool, "message": str}
apply_l2tp(conn)           -> {"ok": bool, "message": str}
get_l2tp_status()          -> {"running": bool, "sessions": [...]}
"""
import ipaddress
import os
import sys

from app.secret_store import decrypt_secret


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def validate_l2tp_config(conn) -> list:
    """
    Validate the L2TP configuration and user list.
    Returns a list of error strings; empty means valid.
    """
    errors = []

    cfg_rows = _rows(conn, "SELECT * FROM l2tp_config WHERE id=1 LIMIT 1")
    if not cfg_rows:
        # No config is not an error — default values will be used
        return []
    cfg = cfg_rows[0]

    server_addr  = (cfg.get("server_address") or "").strip()
    remote_range = (cfg.get("remote_address_range") or "").strip()
    auth_type    = (cfg.get("authentication") or "chap").upper()

    if server_addr:
        try:
            ipaddress.ip_address(server_addr)
        except ValueError:
            errors.append(f"Server address {server_addr!r} is not a valid IP.")

    if remote_range:
        try:
            ipaddress.ip_address(remote_range)
        except ValueError:
            errors.append(f"Remote address range start {remote_range!r} is not a valid IP.")

    if auth_type not in {"CHAP", "PAP", "MSCHAPv2"}:
        errors.append(f"Authentication type {auth_type!r} is not supported. Use CHAP, PAP, or MSCHAPv2.")

    dns1 = (cfg.get("dns_server1") or "").strip()
    dns2 = (cfg.get("dns_server2") or "").strip()
    for label, dns in [("DNS1", dns1), ("DNS2", dns2)]:
        if dns:
            try:
                ipaddress.ip_address(dns)
            except ValueError:
                errors.append(f"{label} {dns!r} is not a valid IP.")

    # Validate users
    users = _rows(conn, "SELECT * FROM l2tp_users ORDER BY id")
    seen_usernames = set()
    for u in users:
        uname = (u.get("username") or "").strip()
        pw_enc = (u.get("password") or "").strip()
        if not uname:
            errors.append(f"L2TP user id={u['id']} has no username.")
            continue
        if uname in seen_usernames:
            errors.append(f"Duplicate L2TP username: {uname!r}.")
        seen_usernames.add(uname)
        if pw_enc:
            pw = decrypt_secret(pw_enc)
            if not pw:
                errors.append(f"L2TP user {uname!r}: password is stored but cannot be decrypted — re-enter it.")
        else:
            errors.append(f"L2TP user {uname!r} has no password set.")

        ip_addr = (u.get("ip_address") or "").strip()
        if ip_addr:
            try:
                ipaddress.ip_address(ip_addr)
            except ValueError:
                errors.append(f"L2TP user {uname!r} has invalid static IP: {ip_addr!r}.")

    return errors

_MPD_DIR    = "/usr/local/etc/mpd5"
_MPD_CONF   = "/usr/local/etc/mpd5/mpd.conf"
_MPD_SECRET = "/usr/local/etc/mpd5/mpd.secret"


def _rows(conn, sql, params=()):
    cur = conn.cursor()
    cur.execute(sql, params)
    return [dict(r) for r in cur.fetchall()]


def _on_freebsd():
    return sys.platform.startswith("freebsd")


def _v(row, key, default=""):
    return row.get(key) or default


def generate_mpd_conf(conn) -> str:
    cfg_rows = _rows(conn, "SELECT * FROM l2tp_config WHERE id=1 LIMIT 1")
    cfg = cfg_rows[0] if cfg_rows else {}

    server_addr   = _v(cfg, "server_address",     "192.168.1.1")
    remote_range  = _v(cfg, "remote_address_range","192.168.1.200")
    subnet_mask   = _v(cfg, "subnet_mask",         "255.255.255.0")
    auth_type     = _v(cfg, "authentication",      "chap").upper()
    dns1          = _v(cfg, "dns_server1",         "")
    dns2          = _v(cfg, "dns_server2",         "")

    # Derive pool range: assume /24, give 50 addresses from remote_range
    pool_start = remote_range
    try:
        import ipaddress
        base = ipaddress.ip_address(remote_range)
        pool_end = str(base + 49)
    except Exception:
        pool_end = remote_range

    lines = [
        "#",
        "# mpd5 L2TP/IPsec configuration",
        "# Auto-generated by Smart Shield — DO NOT EDIT MANUALLY",
        "#",
        "",
        "startup:",
        '    load l2tp_server',
        "",
        "l2tp_server:",
        "    set ippool add pool1 " + pool_start + " " + pool_end,
        "",
        "    create bundle template B_L2TP",
        "    set iface enable proxy-arp",
        "    set iface enable tcpmssfix",
        f"    set ipcp ranges {server_addr}/32 ippool pool1",
    ]

    if dns1:
        lines.append(f"    set ipcp dns {dns1}")
    if dns2:
        lines.append(f"    set ipcp dns {dns2}")

    lines += [
        "",
        "    set bundle enable multilink",
        "    set bundle enable shortseq",
        "    set link yes acfcomp protocomp",
        "    set link no pap",
        "    set link enable " + ("mschapv2" if "CHAP" in auth_type else "pap"),
        f'    set auth authname "l2tpd"',
        "    set link keep-alive 10 60",
        "    set link max-redial 0",
        "",
        "    create link template L_L2TP l2tp",
        "    set l2tp enable incoming",
        "    set l2tp disable originate",
        "    set l2tp enable length",
        f'    set l2tp self {server_addr}',
        "    set link action bundle B_L2TP",
        "",
    ]

    return "\n".join(lines)


def generate_mpd_secret(conn) -> str:
    users = _rows(conn, "SELECT username, password, ip_address FROM l2tp_users ORDER BY id")
    lines = [
        "# mpd5 secret file — auto-generated by Smart Shield",
        "# format: username password [ip-address]",
        "",
    ]
    for u in users:
        username = (u.get("username") or "").strip()
        password = decrypt_secret((u.get("password") or "").strip())
        ip_addr  = (u.get("ip_address") or "").strip()
        if not username or not password:
            continue
        if ip_addr:
            lines.append(f'"{username}" "{password}" {ip_addr}')
        else:
            lines.append(f'"{username}" "{password}"')
    lines.append("")
    return "\n".join(lines)


def write_l2tp_conf(conn) -> dict:
    conf   = generate_mpd_conf(conn)
    secret = generate_mpd_secret(conn)

    if not _on_freebsd():
        return {
            "ok": True,
            "message": "Non-FreeBSD — mpd5 config generated but not written.",
            "conf": conf,
        }

    os.makedirs(_MPD_DIR, exist_ok=True)
    errors = []
    for path, content, mode in [
        (_MPD_CONF,   conf,   0o644),
        (_MPD_SECRET, secret, 0o600),
    ]:
        try:
            with open(path, "w") as fh:
                fh.write(content)
            os.chmod(path, mode)
        except OSError as exc:
            errors.append(f"{path}: {exc}")

    if errors:
        return {"ok": False, "message": "; ".join(errors)}
    return {"ok": True, "message": f"mpd.conf + mpd.secret written to {_MPD_DIR}"}


def apply_l2tp(conn) -> dict:
    """Validate, write mpd5 config, and restart L2TP."""
    validation_errors = validate_l2tp_config(conn)
    if validation_errors:
        return {
            "ok": False,
            "message": "Validation failed: " + " | ".join(validation_errors),
        }
    result = write_l2tp_conf(conn)
    if not result["ok"] or not _on_freebsd():
        return result
    try:
        from app.services.service_manager import service_action
        r = service_action("mpd5", "restart")
        return {
            "ok": r["ok"],
            "message": result["message"] + " | Service: " + r["message"],
        }
    except Exception as exc:
        return {"ok": False, "message": f"Config written but restart failed: {exc}"}


def get_l2tp_status() -> dict:
    if not _on_freebsd():
        return {"running": False, "sessions": [], "message": "Not on FreeBSD"}
    try:
        from app.services.network_service import run_command
        # Ask mpd5 via telnet control interface (port 5006 default)
        r = run_command(["pgrep", "-a", "mpd5"], check=False)
        lines = [l.strip() for l in (r.stdout or "").splitlines() if l.strip()]
        running = bool(lines)

        sessions = []
        if running:
            # sockstat -46 lists open sockets on FreeBSD; filter for L2TP port 1701.
            # netstat -p udp is Linux-specific (on FreeBSD -p means protocol stats).
            ns = run_command(["sockstat", "-46", "-u"], check=False)
            for line in (ns.stdout or "").splitlines():
                if "l2tp" in line.lower() or ":1701" in line:
                    sessions.append(line.strip())

        return {"running": running, "sessions": sessions}
    except Exception as exc:
        return {"running": False, "sessions": [], "message": str(exc)}
