"""
mrtg_writer.py
--------------
Generate and apply the MRTG configuration for Smart Shield network interfaces.

MRTG is driven by cron every 5 minutes. When SNMP is enabled it polls bsnmpd
on localhost via SNMP (ifInOctets/ifOutOctets, interface-by-name lookup).
Falls back to mrtg-probe.sh (netstat -ibn) when SNMP is not configured.

Public API
----------
generate_mrtg_conf(conn)  -> str    # mrtg.cfg content
apply_mrtg(conn)          -> dict   # {"ok": bool, "message": str}
"""

import os
import sys

_MRTG_CONF_PATH  = "/usr/local/etc/mrtg/mrtg.cfg"
_MRTG_WORK_DIR   = "/var/db/smart-shield/mrtg"
_PROBE_SCRIPT    = "/usr/local/share/smart-shield/bsd/mrtg-probe.sh"
_MRTG_LOCK_FILE  = "/var/run/smart-shield/mrtg.lock"


def _iface_name(row: dict, key: str = "assigned_port") -> str:
    return (row.get(key) or "").strip()


def _get_snmp_settings(conn) -> dict:
    """Read SNMP settings from service_state. Returns {} if not configured."""
    try:
        import json
        row = conn.execute(
            "SELECT value_json FROM service_state WHERE key_name='snmp_settings'"
        ).fetchone()
        return json.loads(row["value_json"]) if row else {}
    except Exception:
        return {}


def generate_mrtg_conf(conn) -> str:
    """Build a complete mrtg.cfg from configured WAN and LAN interfaces.

    Uses SNMP (bsnmpd on localhost) when SNMP is enabled and a community
    string is set. Falls back to the mrtg-probe.sh shell script otherwise.
    """
    try:
        wan_row = conn.execute("SELECT assigned_port, description FROM wan_config LIMIT 1").fetchone()
        lan_row = conn.execute("SELECT assigned_port, description FROM lan_config LIMIT 1").fetchone()
    except Exception:
        wan_row = lan_row = None

    wan = dict(wan_row) if wan_row else {}
    lan = dict(lan_row) if lan_row else {}

    wan_iface = _iface_name(wan) or "em0"
    lan_iface = _iface_name(lan) or "em1"
    wan_desc  = (wan.get("description") or "WAN").strip() or "WAN"
    lan_desc  = (lan.get("description") or "LAN").strip() or "LAN"

    interfaces = [
        (wan_iface, wan_desc, "WAN"),
        (lan_iface, lan_desc, "LAN"),
    ]
    # Deduplicate in case WAN and LAN are the same port
    seen = set()
    unique_ifaces = []
    for iface, desc, label in interfaces:
        if iface and iface not in seen:
            seen.add(iface)
            unique_ifaces.append((iface, desc, label))

    # Resolve data source: SNMP (native) or shell script (fallback)
    snmp           = _get_snmp_settings(conn)
    snmp_enabled   = bool(snmp.get("enabled")) and bool((snmp.get("community") or "").strip())
    snmp_community = (snmp.get("community") or "smartshield").strip()
    snmp_port      = int(snmp.get("port") or 161)

    lines = [
        "# =================================================================",
        "# Smart Shield MRTG Configuration",
        "# Generated by app/services/mrtg_writer.py — do not edit manually",
        "# =================================================================",
        "",
        f"WorkDir: {_MRTG_WORK_DIR}",
        "Refresh: 300",
        "Interval: 5",
        "Language: English",
        "Options[_]: growright, bits",
        "",
    ]

    for iface, desc, label in unique_ifaces:
        if snmp_enabled:
            # Native SNMP: \ifname resolves interface by ifDescr (= name on FreeBSD)
            target = f"\\{iface}:{snmp_community}@localhost:{snmp_port}"
        else:
            # Fallback: shell script reads netstat -ibn directly
            target = f"`{_PROBE_SCRIPT} {iface}`"

        lines += [
            f"# ── {label} interface: {iface} ──────────────────────────────",
            f"Target[{iface}]: {target}",
            f"MaxBytes[{iface}]: 125000000",
            f"Title[{iface}]: {label} Traffic — {iface} ({desc})",
            f"PageTop[{iface}]: <h1>{label} — {iface}</h1>",
            f"Options[{iface}]: bits, growright, noinfo",
            "",
        ]

    return "\n".join(lines)


def apply_mrtg(conn) -> dict:
    """Write mrtg.cfg and do a first-run to initialise the log files."""
    conf = generate_mrtg_conf(conn)

    snmp = _get_snmp_settings(conn)
    snmp_active = bool(snmp.get("enabled")) and bool((snmp.get("community") or "").strip())

    if not sys.platform.startswith("freebsd"):
        result = {
            "ok": True,
            "message": "Non-FreeBSD — mrtg.cfg generated but not written.",
            "conf": conf,
        }
        if not snmp_active:
            result["snmp_note"] = (
                "SNMP not enabled — using mrtg-probe.sh fallback. "
                "Enable SNMP for native polling."
            )
        return result

    try:
        os.makedirs(os.path.dirname(_MRTG_CONF_PATH), exist_ok=True)
        os.makedirs(_MRTG_WORK_DIR, exist_ok=True)
    except Exception as exc:
        return {"ok": False, "message": f"Cannot create MRTG directories: {exc}"}

    try:
        with open(_MRTG_CONF_PATH, "w") as fh:
            fh.write(conf)
    except Exception as exc:
        return {"ok": False, "message": f"Cannot write {_MRTG_CONF_PATH}: {exc}"}

    # Prime the RRD / log files with an initial run so graphs appear quickly
    try:
        import subprocess
        result = subprocess.run(
            ["/usr/local/bin/mrtg", _MRTG_CONF_PATH,
             "--lock-file", _MRTG_LOCK_FILE, "--log-level", "0"],
            capture_output=True, text=True, timeout=30
        )
        # MRTG exits non-zero on first run (no log files yet) — that is normal
    except FileNotFoundError:
        return {"ok": False, "message": "mrtg binary not found — is net-mgmt/mrtg installed?"}
    except Exception as exc:
        return {"ok": False, "message": f"MRTG first-run failed: {exc}"}

    result = {"ok": True, "message": f"MRTG config written to {_MRTG_CONF_PATH} and initialised."}
    if not snmp_active:
        result["snmp_note"] = (
            "SNMP not enabled — using mrtg-probe.sh fallback. "
            "Enable SNMP for native polling."
        )
    return result
