"""
mrtg_writer.py
--------------
Generate and apply the MRTG configuration for Smart Shield network interfaces.

MRTG is driven by cron every 5 minutes. When SNMP is enabled it polls bsnmpd
on localhost via SNMP (ifInOctets/ifOutOctets, interface-by-name lookup).
Falls back to mrtg-probe.sh (netstat -ibn) when SNMP is not configured.

Public API
----------
generate_mrtg_conf(conn)  -> str    # mrtg.cfg content
apply_mrtg(conn)          -> dict   # {"ok": bool, "message": str}
"""

import os
import sys

_MRTG_CONF_PATH  = "/usr/local/etc/mrtg/mrtg.cfg"
_MRTG_WORK_DIR   = "/var/db/smart-shield/mrtg"
_PROBE_SCRIPT    = "/usr/local/sbin/mrtg-probe.sh"
_MRTG_LOCK_FILE  = "/var/run/smart-shield/mrtg.lock"


def _iface_name(row: dict, key: str = "assigned_port") -> str:
    return (row.get(key) or "").strip()


def _get_snmp_settings(conn) -> dict:
    """Read SNMP settings from service_state. Returns {} if not configured."""
    try:
        import json
        row = conn.execute(
            "SELECT value_json FROM service_state WHERE key_name='snmp_settings'"
        ).fetchone()
        return json.loads(row["value_json"]) if row else {}
    except Exception:
        return {}


def _discover_interfaces(conn) -> list:
    """
    Return list of active interface names from the DB (interfaces table),
    falling back to ['em0', 'em1'] if no interfaces configured.
    """
    try:
        rows = [dict(r) for r in conn.execute(
            "SELECT interface_name FROM interfaces WHERE enabled=1 OR enabled IS NULL ORDER BY interface_type"
        )]
        ifaces = [r["interface_name"] for r in rows if r.get("interface_name")]
        if ifaces:
            return ifaces
    except Exception:
        pass
    return ["em0", "em1"]


def generate_mrtg_conf(conn) -> str:
    """Build a complete mrtg.cfg from dynamically discovered interfaces.

    Interfaces are discovered from the DB (interfaces table) with fallback
    to WAN/LAN config tables, then ['em0', 'em1'].
    Uses SNMP (bsnmpd on localhost) when SNMP is enabled and a community
    string is set. Falls back to the mrtg-probe.sh shell script otherwise.
    """
    # Prefer DB-discovered interfaces; fall back to WAN/LAN config table lookup
    db_ifaces = _discover_interfaces(conn)

    # Try to enrich with descriptions from wan_config / lan_config
    try:
        wan_row = conn.execute("SELECT assigned_port, description FROM wan_config LIMIT 1").fetchone()
        lan_row = conn.execute("SELECT assigned_port, description FROM lan_config LIMIT 1").fetchone()
    except Exception:
        wan_row = lan_row = None

    wan = dict(wan_row) if wan_row else {}
    lan = dict(lan_row) if lan_row else {}
    wan_iface_cfg = _iface_name(wan) or ""
    lan_iface_cfg = _iface_name(lan) or ""

    def _label_for(iface):
        if iface == wan_iface_cfg:
            return (wan.get("description") or "WAN").strip() or "WAN"
        if iface == lan_iface_cfg:
            return (lan.get("description") or "LAN").strip() or "LAN"
        return iface.upper()

    # Deduplicate
    seen = set()
    unique_ifaces = []
    for iface in db_ifaces:
        if iface and iface not in seen:
            seen.add(iface)
            unique_ifaces.append((iface, _label_for(iface), _label_for(iface)))

    # Resolve data source: SNMP (native) or shell script (fallback)
    snmp           = _get_snmp_settings(conn)
    snmp_enabled   = bool(snmp.get("enabled")) and bool((snmp.get("community") or "").strip())
    snmp_community = (snmp.get("community") or "smartshield").strip()
    snmp_port      = int(snmp.get("port") or 161)

    lines = [
        "# =================================================================",
        "# Smart Shield MRTG Configuration",
        "# Generated by app/services/mrtg_writer.py — do not edit manually",
        "# Interfaces discovered dynamically from DB (interfaces table)",
        "# =================================================================",
        "",
        f"WorkDir: {_MRTG_WORK_DIR}",
        "Refresh: 300",
        "Interval: 5",
        "Language: English",
        "Options[_]: growright, bits",
        "LogFormat: rrdtool",
        "PathAdd: /usr/local/bin",
        "# Log rotation: newsyslog(8) rotates /var/log/mrtg.log weekly.",
        "# Add to /etc/newsyslog.conf:  /var/log/mrtg.log  644 7 * @T00 Z",
        "",
    ]

    for iface, desc, label in unique_ifaces:
        if snmp_enabled:
            # Native SNMP: \ifname resolves interface by ifDescr (= name on FreeBSD)
            target = f"\\{iface}:{snmp_community}@localhost:{snmp_port}"
        else:
            # Fallback: shell script reads netstat -ibn directly
            target = f"`{_PROBE_SCRIPT} {iface}`"

        lines += [
            f"# ── {label} interface: {iface} ──────────────────────────────",
            f"Target[{iface}]: {target}",
            f"MaxBytes[{iface}]: 125000000",
            f"Title[{iface}]: {label} Traffic — {iface} ({desc})",
            f"PageTop[{iface}]: <h1>{label} — {iface}</h1>",
            f"Options[{iface}]: bits, growright, noinfo",
            "",
        ]

    return "\n".join(lines)


def apply_mrtg(conn) -> dict:
    """Write mrtg.cfg and do a first-run to initialise the log files."""
    conf = generate_mrtg_conf(conn)

    snmp = _get_snmp_settings(conn)
    snmp_active = bool(snmp.get("enabled")) and bool((snmp.get("community") or "").strip())

    if not sys.platform.startswith("freebsd"):
        result = {
            "ok": True,
            "rolled_back": False,
            "message": "Non-FreeBSD — mrtg.cfg generated but not written.",
            "conf": conf,
        }
        if not snmp_active:
            result["snmp_note"] = (
                "SNMP not enabled — using mrtg-probe.sh fallback. "
                "Enable SNMP for native polling."
            )
        return result

    try:
        os.makedirs(os.path.dirname(_MRTG_CONF_PATH), exist_ok=True)
        os.makedirs(_MRTG_WORK_DIR, exist_ok=True)
    except Exception as exc:
        return {"ok": False, "rolled_back": False,
                "message": f"Cannot create MRTG directories: {exc}"}

    from app.services.config_file_utils import atomic_write, backup_config, rollback_config
    backup_config(_MRTG_CONF_PATH)
    try:
        atomic_write(_MRTG_CONF_PATH, conf, mode=0o644)
    except Exception as exc:
        return {"ok": False, "rolled_back": False,
                "message": f"Cannot write {_MRTG_CONF_PATH}: {exc}"}

    # Run MRTG twice:
    #   Pass 1: creates .log RRD files (exits non-zero because files are new — that is normal)
    #   Pass 2: reads the .log files and generates initial PNG graph images
    try:
        import subprocess
        _cmd = ["/usr/local/bin/mrtg", _MRTG_CONF_PATH,
                "--lock-file", _MRTG_LOCK_FILE, "--log-level", "0"]
        for _ in range(2):
            subprocess.run(_cmd, capture_output=True, text=True, timeout=30)
    except FileNotFoundError:
        rb = rollback_config(_MRTG_CONF_PATH)
        return {"ok": False, "rolled_back": rb.get("ok", False),
                "message": "mrtg binary not found — is net-mgmt/mrtg installed?"}
    except Exception as exc:
        rb = rollback_config(_MRTG_CONF_PATH)
        return {"ok": False, "rolled_back": rb.get("ok", False),
                "message": f"MRTG first-run failed: {exc}"}

    result = {"ok": True, "rolled_back": False,
              "message": f"MRTG config written to {_MRTG_CONF_PATH} and initialised."}
    if not snmp_active:
        result["snmp_note"] = (
            "SNMP not enabled — using mrtg-probe.sh fallback. "
            "Enable SNMP for native polling."
        )
    return result


# ---------------------------------------------------------------------------
# Status
# ---------------------------------------------------------------------------

def get_mrtg_status() -> dict:
    """
    Return MRTG availability status.

    MRTG is cron-driven (not a persistent daemon), so we report whether the
    binary is installed and when the config/graphs were last updated.
    Returns {"available": bool, "state": str, "last_run": str|None, "message": str}.
    """
    import shutil

    mrtg_bin = "/usr/local/bin/mrtg"
    if not os.path.exists(mrtg_bin) and not shutil.which("mrtg"):
        return {
            "available": False,
            "state":     "unavailable",
            "last_run":  None,
            "message":   "mrtg binary not found — install net-mgmt/mrtg.",
        }

    # Check when the mrtg.cfg was last written (proxy for last successful apply)
    last_run = None
    if os.path.exists(_MRTG_CONF_PATH):
        try:
            import datetime as _dt
            mtime = os.path.getmtime(_MRTG_CONF_PATH)
            last_run = _dt.datetime.fromtimestamp(mtime).isoformat()
        except Exception:
            pass

    # Check whether graph files exist (proxy for successful cron execution)
    graphs_exist = any(
        fname.endswith(".png")
        for fname in (os.listdir(_MRTG_WORK_DIR) if os.path.isdir(_MRTG_WORK_DIR) else [])
    )

    return {
        "available": True,
        "state":     "cron",
        "last_run":  last_run,
        "graphs_ok": graphs_exist,
        "message":   "MRTG runs via cron — not a persistent service.",
    }
