"""
nginx_writer.py
---------------
Generates and applies /usr/local/etc/nginx/nginx.conf from the database.

Replaces the old regex-based _update_nginx_lan_ip() in rc_conf_writer.py
which patched only the listen-IP and would also clobber the loopback
listeners.  Now we own the whole file and regenerate it any time the LAN
IP changes (or any time the reload-all pipeline runs).

The template mirrors what bsd/install.sh writes during install — listen on
${LAN_IP}:{80,443} plus 127.0.0.1:{80,443} so loopback healthchecks always
work, /terminal/ws WebSocket headers for the live CLI, a /portal/ proxy
location, TLS hardening headers, and an `include soc-portal.conf;`.

Public API
----------
generate_nginx_conf(conn)   -> str        full nginx.conf body
validate_nginx_conf(text)   -> (bool,str) runs `nginx -t -c <tmp>` if available
apply_nginx(conn)           -> dict       generate → validate → write → reload
"""

import ipaddress
import os
import re
import sys
import tempfile

_NGINX_CONF_PATH = "/usr/local/etc/nginx/nginx.conf"
_NGINX_BIN       = "/usr/local/sbin/nginx"


def _rows(conn, sql, params=()):
    cur = conn.cursor()
    cur.execute(sql, params)
    return [dict(r) for r in cur.fetchall()]


def _on_freebsd() -> bool:
    return sys.platform.startswith("freebsd")


def _lan_ip(conn) -> str:
    """Resolve the configured LAN IP, defaulting to 192.168.1.1 if absent."""
    rows = _rows(conn, "SELECT ipv4_address FROM lan_config WHERE id=1 LIMIT 1")
    cidr = (rows[0].get("ipv4_address") if rows else "") or ""
    cidr = cidr.strip()
    if not cidr:
        return "192.168.1.1"
    try:
        return str(ipaddress.ip_interface(cidr).ip)
    except ValueError:
        return "192.168.1.1"


def generate_nginx_conf(conn) -> str:
    from app.config import _ss_dir
    lan_ip   = _lan_ip(conn)
    ssl_dir  = os.path.join(_ss_dir("/usr/local/etc"), "ssl")
    ssl_cert = os.path.join(ssl_dir, "cert.pem")
    ssl_key  = os.path.join(ssl_dir, "key.pem")
    return f"""# ============================================================
# Smart Shield — auto-generated nginx.conf
# Generated by app/services/nginx_writer.py
# DO NOT EDIT MANUALLY — regenerate via setup wizard or reload-all
# ============================================================
user www;
worker_processes auto;
pid /var/run/nginx.pid;

events {{
    worker_connections 1024;
}}

http {{
    include       /usr/local/etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile          on;
    keepalive_timeout 65;
    server_tokens     off;

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log warn;

    # ── HTTP (admin vhost) — the admin UI is HTTPS-only ──────────────────────
    # Requests to the appliance's own LAN IP / hostname are redirected to
    # HTTPS so admin login is never served over plain HTTP. Captive portal and
    # static assets stay on HTTP for PF/DNS-redirected unauthenticated clients.
    server {{
        listen      {lan_ip}:80;
        listen      127.0.0.1:80;
        server_name smartshield.local localhost 127.0.0.1 {lan_ip};

        location /portal/ {{
            proxy_pass         http://127.0.0.1:5000;
            proxy_http_version 1.1;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto http;
            proxy_read_timeout 60s;
        }}

        location /static/ {{
            proxy_pass         http://127.0.0.1:5000;
            proxy_http_version 1.1;
            proxy_set_header   Host $host;
        }}

        location / {{
            return 301 https://$host$request_uri;
        }}
    }}

    # ── HTTP (default vhost) — content-policy block pages + captive redirects ──
    # DNS-redirected blocked domains arrive with a foreign Host header and must
    # be answered on plain HTTP (an HTTPS redirect would trip a cert mismatch).
    server {{
        listen      {lan_ip}:80 default_server;
        listen      127.0.0.1:80 default_server;
        server_name _;

        location / {{
            proxy_pass         http://127.0.0.1:5000;
            proxy_http_version 1.1;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto http;
            proxy_read_timeout 60s;
        }}
    }}

    # ── HTTPS — Smart Shield dashboard ───────────────────────────────────────
    server {{
        listen      {lan_ip}:443 ssl;
        listen      127.0.0.1:443 ssl;
        server_name _;

        ssl_certificate     {ssl_cert};
        ssl_certificate_key {ssl_key};

        ssl_protocols             TLSv1.2 TLSv1.3;
        ssl_ciphers               ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256;
        ssl_prefer_server_ciphers on;
        ssl_session_cache         shared:SSL:10m;
        ssl_session_timeout       1d;
        ssl_session_tickets       off;

        add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
        add_header X-Frame-Options           DENY                                           always;
        add_header X-Content-Type-Options    nosniff                                        always;
        add_header X-XSS-Protection          "1; mode=block"                                always;
        add_header Referrer-Policy           "strict-origin-when-cross-origin"              always;

        client_max_body_size 260m;

        location /terminal/ws {{
            proxy_pass         http://127.0.0.1:5000;
            proxy_http_version 1.1;
            proxy_set_header   Upgrade    $http_upgrade;
            proxy_set_header   Connection "upgrade";
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }}

        location /portal/ {{
            proxy_pass         http://127.0.0.1:5000;
            proxy_http_version 1.1;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto https;
            proxy_read_timeout 60s;
        }}

        location / {{
            proxy_pass         http://127.0.0.1:5000;
            proxy_http_version 1.1;

            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;

            proxy_connect_timeout  90s;
            proxy_read_timeout    300s;
            proxy_send_timeout     90s;
        }}
    }}

    include /usr/local/etc/nginx/soc-portal.conf;
}}
"""


_SOC_PORTAL_PLACEHOLDER = (
    "# Placeholder — replaced when admin enables System → SOC Portal Settings.\n"
)


def _ensure_soc_portal_placeholder() -> None:
    """
    Self-heal: the http block always references /usr/local/etc/nginx/soc-portal.conf,
    so on FreeBSD ensure the file exists before `nginx -t`. install.sh creates this on
    fresh installs; this guard covers systems where the file was removed out-of-band.
    """
    if not _on_freebsd():
        return
    path = "/usr/local/etc/nginx/soc-portal.conf"
    if os.path.exists(path):
        return
    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(_SOC_PORTAL_PLACEHOLDER)
        os.chmod(path, 0o644)
    except OSError:
        pass


_LISTEN_RE = re.compile(
    r"^(?P<lead>\s*)listen\s+(?P<ip>\d{1,3}(?:\.\d{1,3}){3}):(?P<port>\d+)(?P<rest>.*?);",
    re.MULTILINE,
)


def _to_validation_variant(text: str) -> str:
    """
    Rewrite every ``listen <ip>:<port> ...;`` to a unique unprivileged port
    on ``127.0.0.1``. ``nginx -t`` actually opens listen sockets, so
    validating the real LAN-IP-bound config returns EADDRNOTAVAIL whenever
    that IP is not currently on an interface (install before §6b plumbs
    it, or a wizard LAN-IP change before apply_interface_config runs).
    The on-disk config written by apply_nginx is unchanged — only the
    transient text fed to ``nginx -t`` uses these loopback substitutes.

    All substitutes stay on ``127.0.0.1`` and differ only by port. FreeBSD
    binds only ``127.0.0.1`` to lo0 by default (unlike Linux, where the whole
    127.0.0.0/8 is loopback), so the earlier scheme of incrementing the last
    octet — 127.0.0.2, 127.0.0.3 … for repeated listens on a port — failed
    with EADDRNOTAVAIL on the second listen. Incrementing the port instead
    keeps every socket bindable while remaining unique (no ``duplicate
    listen`` / ``default_server`` conflicts).
    """
    seen: dict[int, int] = {}

    def _swap(m: "re.Match[str]") -> str:
        port = int(m.group("port"))
        base = {80: 8080, 443: 8443}.get(port, port + 8000)
        seen[base] = seen.get(base, -1) + 1
        return f'{m.group("lead")}listen 127.0.0.1:{base + seen[base]}{m.group("rest")};'

    return _LISTEN_RE.sub(_swap, text)


def validate_nginx_conf(text: str) -> tuple:
    """
    Write *text* to a temp file and run ``nginx -t -c <tmp>``.
    Returns ``(True, "")`` on success, ``(False, error_output)`` otherwise.
    Skipped (and reported OK) on non-FreeBSD or when nginx is not installed.

    Listen lines are rewritten to loopback unprivileged ports for the test
    (see _to_validation_variant). Syntax, TLS, and include resolution are
    fully exercised; only the live socket bind is deferred to service start.
    """
    if not _on_freebsd():
        return (True, "skipped-non-freebsd")
    if not os.path.exists(_NGINX_BIN):
        return (True, "skipped-nginx-not-found")

    tmp_path = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".conf", delete=False, prefix="ss_nginx_"
        ) as f:
            f.write(_to_validation_variant(text))
            tmp_path = f.name
        from app.services.network_service import run_command
        r = run_command([_NGINX_BIN, "-t", "-c", tmp_path], check=False)
        ok  = r.returncode == 0
        msg = (r.stderr or r.stdout or "").strip()
        return (ok, msg)
    except Exception as exc:
        return (False, str(exc))
    finally:
        if tmp_path:
            try:
                os.unlink(tmp_path)
            except OSError:
                pass


def apply_nginx(conn) -> dict:
    """
    Generate nginx.conf, validate via `nginx -t -c <tmp>`, atomically write,
    reload nginx, and roll back to the known-good file if reload fails.
    On non-FreeBSD: generate only (no writes, no reload).
    Returns ``{"ok": bool, "message": str, "conf": str}``.
    """
    conf = generate_nginx_conf(conn)
    _ensure_soc_portal_placeholder()

    ok, err = validate_nginx_conf(conf)
    if not ok:
        return {"ok": False, "message": f"nginx -t failed: {err}", "conf": conf}

    if not _on_freebsd():
        return {"ok": True, "message": "Non-FreeBSD — nginx.conf generated (validation OK).", "conf": conf}

    from app.services.config_file_utils import apply_with_rollback
    from app.services.service_manager import service_action

    result = apply_with_rollback(
        _NGINX_CONF_PATH,
        conf,
        restart_fn=lambda: service_action("nginx", "reload"),
        mode=0o644,
        rollback_on_restart_failure=False,
    )
    message = result.get("message", "")
    if not result.get("ok"):
        lan_ip = _lan_ip(conn)
        message = (
            f"nginx config written but reload failed: {message} — check that "
            f"{lan_ip} is on the LAN interface, then run `service nginx restart`."
        )
    return {
        "ok": result.get("ok", False),
        "message": message,
        "conf": conf,
        "rolled_back": result.get("rolled_back", False),
    }
