"""
ntp_writer.py
-------------
Generates ntpd.conf for FreeBSD's base-system ntpd (IETF NTPv4 daemon).
FreeBSD ships ntpd in base; no extra package is needed.

Public API
----------
generate_ntp_conf(settings)  -> str
validate_ntp(settings)       -> list[str]
apply_ntp(conn)              -> dict
get_ntp_status()             -> dict
get_ntp_sync_status()        -> dict
"""

import ipaddress
import sys
from typing import Any

_NTP_CONF_PATH = "/etc/ntp.conf"
_NTP_DRIFT_PATH = "/var/db/ntpd.drift"


# ---------------------------------------------------------------------------
# Default settings
# ---------------------------------------------------------------------------

DEFAULT_SETTINGS = {
    "enabled": True,
    "servers": ["0.freebsd.pool.ntp.org", "1.freebsd.pool.ntp.org",
                "2.freebsd.pool.ntp.org", "3.freebsd.pool.ntp.org"],
    "interface": "",
    "serve_local": True,
    "log_peers": False,
    "allowed_networks": ["127.0.0.0/8"],
    "restrict_default": True,
}


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def validate_ntp(settings: dict) -> list:
    """Return a list of error strings; empty means valid."""
    errors = []
    servers = settings.get("servers") or []
    if not servers:
        errors.append("At least one NTP time server is required.")
    else:
        for srv in servers:
            s = (srv or "").strip()
            if not s:
                continue
            # Accept both hostnames and IPs
            if " " in s or len(s) > 253:
                errors.append(f"Invalid NTP server: {s!r}")

    allowed = settings.get("allowed_networks") or []
    for net in allowed:
        n = (net or "").strip()
        if not n:
            continue
        try:
            ipaddress.ip_network(n, strict=False)
        except ValueError:
            errors.append(f"Invalid network in allowed_networks: {n!r}")

    return errors


# ---------------------------------------------------------------------------
# Config generator
# ---------------------------------------------------------------------------

def generate_ntp_conf(settings: dict) -> str:
    servers = settings.get("servers") or DEFAULT_SETTINGS["servers"]
    interface = (settings.get("interface") or "").strip()
    serve_local = bool(settings.get("serve_local", True))
    restrict_default = bool(settings.get("restrict_default", True))
    allowed = settings.get("allowed_networks") or ["127.0.0.0/8"]
    log_peers = bool(settings.get("log_peers", False))

    lines = [
        "# ============================================================",
        "# Smart Shield — auto-generated ntp.conf",
        "# Generated by app/services/ntp_writer.py",
        "# Backend: FreeBSD base-system ntpd",
        "# DO NOT EDIT MANUALLY",
        "# ============================================================",
        "",
        f"driftfile {_NTP_DRIFT_PATH}",
        "",
        # Step the clock at ANY offset instead of exiting on a large one. On a VM
        # (snapshot/suspend) or a box with a dead RTC battery the boot-time offset
        # routinely exceeds ntpd's 1000s panic threshold, so without this ntpd
        # logs "Clock offset exceeds panic threshold / Set system clock by hand"
        # and dies — leaving the clock wrong, which breaks TLS cert validation
        # (browsers reject HTTPS as "not yet valid"). Pairs with ntpd_sync_on_start
        # (-g) so the clock self-corrects once a time server is reachable.
        "tinker panic 0",
        "",
    ]

    # Time servers
    lines.append("# ── Time servers ──")
    for srv in servers:
        s = (srv or "").strip()
        if s:
            lines.append(f"server {s} iburst")
    lines.append("")

    # Interface binding
    if interface:
        lines.append(f"interface listen {interface}")
        lines.append("")

    # Access restrictions
    if restrict_default:
        lines += [
            "# Default deny (restrict outbound queries to listed servers only)",
            "restrict default kod nomodify notrap nopeer noquery",
            "restrict -6 default kod nomodify notrap nopeer noquery",
        ]

    lines += [
        "restrict 127.0.0.1",
        "restrict ::1",
    ]
    for net in allowed:
        n = (net or "").strip()
        if n and n not in ("127.0.0.0/8",):
            try:
                network = ipaddress.ip_network(n, strict=False)
                addr = str(network.network_address)
                mask = str(network.netmask)
                lines.append(f"restrict {addr} mask {mask} nomodify notrap")
            except ValueError:
                pass
    lines.append("")

    # Local clock fallback
    if serve_local:
        lines += [
            "# Local fallback clock (low stratum to prefer real servers)",
            "server 127.127.1.0",
            "fudge 127.127.1.0 stratum 10",
            "",
        ]

    # Logging
    if log_peers:
        lines.append("logfile /var/log/ntpd.log")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Write + apply
# ---------------------------------------------------------------------------

def apply_ntp(conn) -> dict:
    """Load NTP settings from DB service_state, validate, write, restart ntpd."""
    import json
    rows = conn.execute(
        "SELECT value_json FROM service_state WHERE key_name='ntp_settings'"
    ).fetchone()
    settings = json.loads(rows["value_json"]) if rows else DEFAULT_SETTINGS

    errors = validate_ntp(settings)
    if errors:
        return {"ok": False, "message": "Validation failed: " + " | ".join(errors)}

    conf = generate_ntp_conf(settings)

    if not sys.platform.startswith("freebsd"):
        return {"ok": True, "rolled_back": False,
                "message": "Non-FreeBSD — ntpd.conf generated but not written.", "conf": conf}

    from app.services.config_file_utils import apply_with_rollback
    from app.services.service_manager import service_action, sysrc_set
    enabled = bool(settings.get("enabled", True))

    def _restart():
        if enabled:
            sysrc_set("ntpd_enable", "YES")
            return service_action("ntpd", "restart")
        else:
            sysrc_set("ntpd_enable", "NO")
            return service_action("ntpd", "stop")

    result = apply_with_rollback(_NTP_CONF_PATH, conf, _restart,
                                 validate_fn=_validate_ntp_conf)
    return {**result, "conf": conf}


def _validate_ntp_conf(tmp_path: str) -> dict:
    """Offline sanity check of a staged ntp.conf before it goes live.

    ntpd has no cheap ``-t`` syntax-check mode (``ntpd -d -n -q`` actually
    queries the network), so we do a lightweight Python check: the file must be
    readable and carry at least one time source plus a driftfile line.
    """
    import re
    try:
        with open(tmp_path, encoding="utf-8") as fh:
            text = fh.read()
    except OSError as exc:
        return {"ok": False, "message": f"cannot read staged ntp.conf: {exc}", "output": ""}
    if not re.search(r"^\s*(server|pool)\s+\S+", text, re.MULTILINE):
        return {"ok": False, "message": "ntp.conf has no server/pool directive", "output": ""}
    if "driftfile" not in text:
        return {"ok": False, "message": "ntp.conf missing driftfile directive", "output": ""}
    return {"ok": True, "message": "ntp.conf sanity check OK", "output": ""}


# ---------------------------------------------------------------------------
# Status
# ---------------------------------------------------------------------------

def get_ntp_status() -> dict:
    if not sys.platform.startswith("freebsd"):
        return {"running": False, "state": "dry-run", "message": "Non-FreeBSD host."}
    from app.services.service_manager import service_action
    r = service_action("ntpd", "status")
    running = r["ok"] and "running" in r.get("message", "").lower()
    return {"running": running, "state": "running" if running else "stopped",
            "message": r.get("message", "")}


def get_ntp_sync_status() -> dict:
    """Run ntpq -p to get peer synchronisation status."""
    if not sys.platform.startswith("freebsd"):
        return {"ok": True, "peers": [], "message": "Non-FreeBSD host."}
    try:
        from app.services.network_service import run_command
        r = run_command(["ntpq", "-p"], check=False, timeout_seconds=5)
        lines = (r.stdout or "").splitlines()
        peers = []
        for line in lines[2:]:  # skip header lines
            parts = line.split()
            if len(parts) >= 8:
                peers.append({
                    "remote": parts[0], "refid": parts[1],
                    "stratum": parts[2], "type": parts[3],
                    "poll": parts[4], "reach": parts[5],
                    "delay": parts[6], "offset": parts[7],
                    "jitter": parts[8] if len(parts) > 8 else "",
                })
        return {"ok": True, "peers": peers}
    except Exception as exc:
        return {"ok": False, "peers": [], "message": str(exc)}


def force_ntp_sync() -> dict:
    """
    Force an immediate NTP time synchronisation using ``ntpdate`` or ``ntpd -g``.
    Useful after a large clock drift or initial setup.
    Returns ``{"ok": bool, "message": str, "offset_ms": float|None}``.
    On non-FreeBSD: dry-run.
    """
    if not sys.platform.startswith("freebsd"):
        return {"ok": True, "message": "Non-FreeBSD — NTP force-sync skipped.", "offset_ms": None}

    import shutil
    from app.services.network_service import run_command

    # Prefer ntpdate for a one-shot step-correction
    if shutil.which("ntpdate"):
        try:
            r = run_command(["ntpdate", "-u", "pool.ntp.org"], check=False, timeout_seconds=15)
            ok  = r.returncode == 0
            out = (r.stdout or r.stderr or "").strip()
            # Parse offset from ntpdate output: "adjust time server ... offset N.NNNNNN sec"
            import re as _re
            m = _re.search(r"offset\s+(-?\d+\.\d+)", out)
            offset_ms = round(float(m.group(1)) * 1000, 3) if m else None
            return {
                "ok":        ok,
                "message":   "NTP sync completed." if ok else f"ntpdate error: {out}",
                "offset_ms": offset_ms,
            }
        except Exception as exc:
            return {"ok": False, "message": str(exc), "offset_ms": None}

    # Fallback: kick the running ntpd with -g (step correction allowed once)
    try:
        from app.services.service_manager import service_action
        r = service_action("ntpd", "restart")
        return {
            "ok":        r["ok"],
            "message":   r.get("message", ""),
            "offset_ms": None,
        }
    except Exception as exc:
        return {"ok": False, "message": str(exc), "offset_ms": None}
