"""
ntp_writer.py
-------------
Generates ntpd.conf for FreeBSD's base-system ntpd (IETF NTPv4 daemon).
FreeBSD ships ntpd in base; no extra package is needed.

Public API
----------
generate_ntp_conf(settings)  -> str
validate_ntp(settings)       -> list[str]
apply_ntp(conn)              -> dict
get_ntp_status()             -> dict
get_ntp_sync_status()        -> dict
"""

import ipaddress
import sys
from typing import Any

_NTP_CONF_PATH = "/etc/ntp.conf"
_NTP_DRIFT_PATH = "/var/db/ntpd.drift"


# ---------------------------------------------------------------------------
# Default settings
# ---------------------------------------------------------------------------

DEFAULT_SETTINGS = {
    "enabled": True,
    "servers": ["0.freebsd.pool.ntp.org", "1.freebsd.pool.ntp.org",
                "2.freebsd.pool.ntp.org", "3.freebsd.pool.ntp.org"],
    "interface": "",
    "serve_local": True,
    "log_peers": False,
    "allowed_networks": ["127.0.0.0/8"],
    "restrict_default": True,
}


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def validate_ntp(settings: dict) -> list:
    """Return a list of error strings; empty means valid."""
    errors = []
    servers = settings.get("servers") or []
    if not servers:
        errors.append("At least one NTP time server is required.")
    else:
        for srv in servers:
            s = (srv or "").strip()
            if not s:
                continue
            # Accept both hostnames and IPs
            if " " in s or len(s) > 253:
                errors.append(f"Invalid NTP server: {s!r}")

    allowed = settings.get("allowed_networks") or []
    for net in allowed:
        n = (net or "").strip()
        if not n:
            continue
        try:
            ipaddress.ip_network(n, strict=False)
        except ValueError:
            errors.append(f"Invalid network in allowed_networks: {n!r}")

    return errors


# ---------------------------------------------------------------------------
# Config generator
# ---------------------------------------------------------------------------

def generate_ntp_conf(settings: dict) -> str:
    servers = settings.get("servers") or DEFAULT_SETTINGS["servers"]
    interface = (settings.get("interface") or "").strip()
    serve_local = bool(settings.get("serve_local", True))
    restrict_default = bool(settings.get("restrict_default", True))
    allowed = settings.get("allowed_networks") or ["127.0.0.0/8"]
    log_peers = bool(settings.get("log_peers", False))

    lines = [
        "# ============================================================",
        "# Smart Shield — auto-generated ntp.conf",
        "# Generated by app/services/ntp_writer.py",
        "# Backend: FreeBSD base-system ntpd",
        "# DO NOT EDIT MANUALLY",
        "# ============================================================",
        "",
        f"driftfile {_NTP_DRIFT_PATH}",
        "",
    ]

    # Time servers
    lines.append("# ── Time servers ──")
    for srv in servers:
        s = (srv or "").strip()
        if s:
            lines.append(f"server {s} iburst")
    lines.append("")

    # Interface binding
    if interface:
        lines.append(f"interface listen {interface}")
        lines.append("")

    # Access restrictions
    if restrict_default:
        lines += [
            "# Default deny (restrict outbound queries to listed servers only)",
            "restrict default kod nomodify notrap nopeer noquery",
            "restrict -6 default kod nomodify notrap nopeer noquery",
        ]

    lines += [
        "restrict 127.0.0.1",
        "restrict ::1",
    ]
    for net in allowed:
        n = (net or "").strip()
        if n and n not in ("127.0.0.0/8",):
            try:
                network = ipaddress.ip_network(n, strict=False)
                addr = str(network.network_address)
                mask = str(network.netmask)
                lines.append(f"restrict {addr} mask {mask} nomodify notrap")
            except ValueError:
                pass
    lines.append("")

    # Local clock fallback
    if serve_local:
        lines += [
            "# Local fallback clock (low stratum to prefer real servers)",
            "server 127.127.1.0",
            "fudge 127.127.1.0 stratum 10",
            "",
        ]

    # Logging
    if log_peers:
        lines.append("logfile /var/log/ntpd.log")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Write + apply
# ---------------------------------------------------------------------------

def apply_ntp(conn) -> dict:
    """Load NTP settings from DB service_state, validate, write, restart ntpd."""
    import json
    rows = conn.execute(
        "SELECT value_json FROM service_state WHERE key_name='ntp_settings'"
    ).fetchone()
    settings = json.loads(rows["value_json"]) if rows else DEFAULT_SETTINGS

    errors = validate_ntp(settings)
    if errors:
        return {"ok": False, "message": "Validation failed: " + " | ".join(errors)}

    conf = generate_ntp_conf(settings)

    if not sys.platform.startswith("freebsd"):
        return {"ok": True, "message": "Non-FreeBSD — ntpd.conf generated but not written.", "conf": conf}

    try:
        with open(_NTP_CONF_PATH, "w") as fh:
            fh.write(conf)
    except OSError as exc:
        return {"ok": False, "message": str(exc), "conf": conf}

    from app.services.service_manager import service_action, sysrc_set
    enabled = bool(settings.get("enabled", True))
    if enabled:
        sysrc_set("ntpd_enable", "YES")
        r = service_action("ntpd", "restart")
    else:
        sysrc_set("ntpd_enable", "NO")
        r = service_action("ntpd", "stop")
    return {"ok": r["ok"], "message": r["message"], "conf": conf}


# ---------------------------------------------------------------------------
# Status
# ---------------------------------------------------------------------------

def get_ntp_status() -> dict:
    if not sys.platform.startswith("freebsd"):
        return {"running": False, "state": "dry-run", "message": "Non-FreeBSD host."}
    from app.services.service_manager import service_action
    r = service_action("ntpd", "status")
    running = r["ok"] and "running" in r.get("message", "").lower()
    return {"running": running, "state": "running" if running else "stopped",
            "message": r.get("message", "")}


def get_ntp_sync_status() -> dict:
    """Run ntpq -p to get peer synchronisation status."""
    if not sys.platform.startswith("freebsd"):
        return {"ok": True, "peers": [], "message": "Non-FreeBSD host."}
    try:
        from app.services.network_service import run_command
        r = run_command(["ntpq", "-p"], check=False, timeout_seconds=5)
        lines = (r.stdout or "").splitlines()
        peers = []
        for line in lines[2:]:  # skip header lines
            parts = line.split()
            if len(parts) >= 8:
                peers.append({
                    "remote": parts[0], "refid": parts[1],
                    "stratum": parts[2], "type": parts[3],
                    "poll": parts[4], "reach": parts[5],
                    "delay": parts[6], "offset": parts[7],
                    "jitter": parts[8] if len(parts) > 8 else "",
                })
        return {"ok": True, "peers": peers}
    except Exception as exc:
        return {"ok": False, "peers": [], "message": str(exc)}
