"""
openvpn_writer.py
-----------------
Generates OpenVPN server config files from Smart Shield's openvpn_servers table.
Each server gets its own file at /usr/local/etc/openvpn/server-<id>.conf.

Public API
----------
generate_server_conf(row)        -> str
write_openvpn_configs(conn)      -> {"ok": bool, "message": str, "configs": [...]}
"""

import os
import sys

_OPENVPN_DIR = "/usr/local/etc/openvpn"


def _rows(conn, sql, params=()):
    cur = conn.cursor()
    cur.execute(sql, params)
    return [dict(r) for r in cur.fetchall()]


def generate_server_conf(row: dict) -> str:
    sid      = row.get("id", 1)
    proto    = (row.get("protocol") or "udp4").lower()
    port     = row.get("local_port") or 1194
    dev      = (row.get("device_mode") or "tun").lower()
    tunnel   = (row.get("tunnel_network") or "10.8.0.0/24").strip()
    redirect = row.get("redirect_gateway", 0)
    local_net = (row.get("local_network") or "").strip()
    max_clients = row.get("max_clients") or 100
    compress = (row.get("compression") or "").strip()
    desc     = (row.get("description") or f"server-{sid}").strip()

    # Derive subnet/mask from tunnel_network
    tun_subnet = "10.8.0.0"
    tun_mask   = "255.255.255.0"
    try:
        import ipaddress
        net = ipaddress.ip_network(tunnel, strict=False)
        tun_subnet = str(net.network_address)
        tun_mask   = str(net.netmask)
    except Exception:
        pass

    # OpenVPN uses tcp/udp not tcp4/udp4 in server directives
    proto_clean = proto.replace("4", "").replace("6", "")

    lines = [
        f"# Smart Shield — OpenVPN Server {sid}: {desc}",
        f"# Auto-generated by app/services/openvpn_writer.py",
        "",
        f"port {port}",
        f"proto {proto_clean}",
        f"dev {dev}{sid}",
        "",
        f"server {tun_subnet} {tun_mask}",
        "ifconfig-pool-persist /var/log/openvpn/ipp.txt",
        "",
    ]

    if redirect:
        lines.append('push "redirect-gateway def1 bypass-dhcp"')
    if local_net:
        lines.append(f'push "route {local_net.replace("/", " ")}"')

    lines += [
        "",
        f"max-clients {max_clients}",
        "keepalive 10 120",
        "",
    ]

    if compress:
        lines.append(f"compress {compress}")

    lines += [
        "persist-key",
        "persist-tun",
        "",
        f"status /var/log/openvpn/status-{sid}.log",
        f"log-append /var/log/openvpn/server-{sid}.log",
        "verb 3",
        "",
        "# Key / cert paths — set these to your actual certificate paths",
        f"ca   /usr/local/etc/openvpn/keys/server{sid}-ca.crt",
        f"cert /usr/local/etc/openvpn/keys/server{sid}.crt",
        f"key  /usr/local/etc/openvpn/keys/server{sid}.key",
        f"dh   /usr/local/etc/openvpn/keys/dh.pem",
        "tls-auth /usr/local/etc/openvpn/keys/ta.key 0",
    ]

    return "\n".join(lines) + "\n"


def write_openvpn_configs(conn) -> dict:
    servers = _rows(conn, "SELECT * FROM openvpn_servers WHERE disabled=0 ORDER BY id")

    if not servers:
        return {"ok": True, "message": "No enabled OpenVPN servers to configure.", "configs": []}

    configs = []

    for row in servers:
        sid  = row.get("id")
        conf = generate_server_conf(row)
        configs.append({"id": sid, "conf": conf})

    if not sys.platform.startswith("freebsd"):
        return {
            "ok": True,
            "message": f"Non-FreeBSD — {len(configs)} OpenVPN config(s) generated but not written.",
            "configs": configs,
        }

    os.makedirs(_OPENVPN_DIR, exist_ok=True)
    os.makedirs("/var/log/openvpn", exist_ok=True)

    errors = []
    for item in configs:
        path = os.path.join(_OPENVPN_DIR, f"server-{item['id']}.conf")
        try:
            with open(path, "w") as fh:
                fh.write(item["conf"])
            item["path"] = path
        except OSError as exc:
            errors.append(f"server-{item['id']}: {exc}")

    if errors:
        return {"ok": False, "message": "; ".join(errors), "configs": configs}
    return {"ok": True, "message": f"Wrote {len(configs)} OpenVPN config(s) to {_OPENVPN_DIR}", "configs": configs}
