"""
pppoe_writer.py
---------------
Generates /etc/ppp/ppp.conf for PPPoE WAN connections on FreeBSD and manages
the base-system ppp(8) daemon.

Design
------
* PPPoE uses the FreeBSD base ppp(8) daemon — no extra package required.
* The physical NIC (e.g. em0) is read from wan_config.assigned_port.
* ppp creates a tun0 interface when the session comes up; pf rules must
  reference tun0 as the WAN interface in PPPoE mode (handled by pf_generator).
* The connection label used throughout is PPP_LABEL = "smartshield_wan".

Public API
----------
validate_pppoe(wan, ...)  -> list[str]   (empty list = valid)
generate_ppp_conf(conn)   -> str
write_ppp_conf(conn)      -> {"ok": bool, "message": str, "conf": str}
apply_pppoe(conn)         -> {"ok": bool, "message": str}
get_pppoe_status()        -> {"running": bool, "interface": str,
                              "ip_address": str, "message": str}
disconnect_pppoe()        -> {"ok": bool, "message": str}
"""

import os
import re
import sys

from app.services.network_service import run_command, FreeBSDNetworkError
from app.secret_store import decrypt_secret

_PPP_CONF_PATH = "/etc/ppp/ppp.conf"
_PPP_LABEL     = "smartshield_wan"
_PPP_TUN_IFACE = "tun0"


def _rows(conn, sql, params=()):
    cur = conn.cursor()
    cur.execute(sql, params)
    return [dict(r) for r in cur.fetchall()]


def _on_freebsd() -> bool:
    return sys.platform.startswith("freebsd")


def _wan(conn) -> dict:
    rows = _rows(conn, "SELECT * FROM wan_config WHERE id=1")
    return rows[0] if rows else {}


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def validate_pppoe(wan: dict, physical_nics=None) -> list:
    """Validate a PPPoE WAN config payload before write/apply.

    Returns a list of human-readable error messages (empty = valid). Accepts
    a dict with the wan_config columns (``assigned_port``, ``username``,
    ``password``, optional ``service``). ``physical_nics`` is the list
    ``network_service.list_physical_nics()`` returns; pass an empty list /
    ``None`` to skip the NIC-membership check (off-FreeBSD that helper
    returns ``[]``, so we can't enforce membership there).
    """
    errors = []
    if not (wan.get("username") or "").strip():
        errors.append("PPPoE username is required.")
    if not (wan.get("password") or "").strip():
        errors.append("PPPoE password is required.")

    iface = (wan.get("assigned_port") or "").strip()
    if not iface:
        errors.append("Assigned WAN port is required for PPPoE.")
    elif physical_nics:
        nic_names = {
            (n.get("name") if isinstance(n, dict) else str(n)) for n in physical_nics
        }
        if iface not in nic_names:
            errors.append(
                f"Assigned port {iface!r} is not a physical NIC "
                f"(detected: {', '.join(sorted(nic_names)) or 'none'})."
            )

    service = (wan.get("service") or "").strip()
    if service and not re.fullmatch(r"[A-Za-z0-9_-]+", service):
        errors.append("PPPoE service name must contain only letters, digits, '_' or '-'.")
    return errors


# ---------------------------------------------------------------------------
# Config generator
# ---------------------------------------------------------------------------

def generate_ppp_conf(conn) -> str:
    """
    Build a /etc/ppp/ppp.conf from wan_config.

    The output contains a 'default:' stanza (logging) and a
    'smartshield_wan:' stanza with the ISP credentials and connection
    settings.  Starting the daemon:
        ppp -ddial smartshield_wan     # always-on (reconnects on drop)
        ppp -auto  smartshield_wan     # dial-on-demand
    """
    wan = _wan(conn)

    physical_iface = (wan.get("assigned_port") or "em0").strip()
    username       = (wan.get("username") or "").strip()
    password       = decrypt_secret((wan.get("password") or "").strip())
    dial_on_demand = bool(wan.get("dial_on_demand", 0))
    idle_timeout   = int(wan.get("idle_timeout") or 0)

    # MTU for PPPoE is 1492 (Ethernet 1500 − 8-byte PPPoE header).
    # Use the admin-configured value if set, else default.
    raw_mtu = (wan.get("mtu") or "").strip()
    mtu = raw_mtu if raw_mtu.isdigit() else "1492"
    mru = mtu  # MRU should match MTU for PPPoE

    # Idle timeout: 0 means never disconnect (always-on).
    # For dial-on-demand, use the configured value (default 300 s).
    if dial_on_demand:
        timeout_val = str(idle_timeout) if idle_timeout > 0 else "300"
    else:
        timeout_val = "0"

    lines = [
        "# ============================================================",
        "# Smart Shield — auto-generated ppp.conf (PPPoE WAN)",
        "# Generated by app/services/pppoe_writer.py",
        "# DO NOT EDIT MANUALLY — changes will be overwritten",
        "# ============================================================",
        "",
        "default:",
        "    set log Phase Chat LCP IPCP CCP tun command",
        "",
        f"{_PPP_LABEL}:",
        f"    set device PPPoE:{physical_iface}",
        "    set speed sync",
        f"    set mru {mru}",
        f"    set mtu {mtu}",
        "    set ctsrts off",
        # mssfixup clamps TCP MSS inside PPPoE to prevent fragmentation
        "    enable mssfixup",
        f'    set authname "{username}"',
        f'    set authkey "{password}"',
        f"    set timeout {timeout_val}",
        "    add default HISADDR",
        "    enable dns",
        "",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Write config to disk
# ---------------------------------------------------------------------------

def write_ppp_conf(conn) -> dict:
    conf = generate_ppp_conf(conn)

    if not _on_freebsd():
        return {
            "ok": True,
            "message": "Non-FreeBSD — ppp.conf generated but not written.",
            "conf": conf,
        }

    os.makedirs("/etc/ppp", exist_ok=True)
    try:
        with open(_PPP_CONF_PATH, "w") as fh:
            fh.write(conf)
        os.chmod(_PPP_CONF_PATH, 0o600)
        return {"ok": True, "message": f"Written to {_PPP_CONF_PATH}", "conf": conf}
    except OSError as exc:
        return {"ok": False, "message": str(exc), "conf": conf}


# ---------------------------------------------------------------------------
# Apply: write config + (re)start ppp daemon
# ---------------------------------------------------------------------------

def apply_pppoe(conn) -> dict:
    """
    Write /etc/ppp/ppp.conf then (re)start the ppp(8) daemon.

    * always-on  (dial_on_demand=0): ppp -ddial smartshield_wan
    * dial-on-demand (dial_on_demand=1): ppp -auto smartshield_wan

    Any existing ppp process using our label is killed first so the new
    credentials and settings take effect immediately.
    """
    write_result = write_ppp_conf(conn)
    if not write_result["ok"]:
        return write_result

    if not _on_freebsd():
        return {"ok": True, "message": "Non-FreeBSD — PPPoE daemon start skipped."}

    wan = _wan(conn)
    dial_on_demand = bool(wan.get("dial_on_demand", 0))

    # Kill any running ppp session for this label before starting a new one.
    run_command(["pkill", "-f", f"ppp.*{_PPP_LABEL}"], check=False)

    mode = "-auto" if dial_on_demand else "-ddial"
    try:
        run_command(["/usr/sbin/ppp", mode, _PPP_LABEL], check=True)
        mode_label = "dial-on-demand" if dial_on_demand else "always-on"
        return {
            "ok": True,
            "message": (
                f"PPPoE session started on {_PPP_TUN_IFACE} "
                f"(mode: {mode_label}). "
                "Allow a few seconds for the link to come up."
            ),
        }
    except FreeBSDNetworkError as exc:
        return {"ok": False, "message": f"ppp failed to start: {exc}"}


# ---------------------------------------------------------------------------
# Status
# ---------------------------------------------------------------------------

def get_pppoe_status() -> dict:
    """Return running state of the PPPoE session."""
    if not _on_freebsd():
        return {
            "running": False,
            "interface": _PPP_TUN_IFACE,
            "ip_address": "",
            "message": "Not on FreeBSD",
        }

    r = run_command(["pgrep", "-f", f"ppp.*{_PPP_LABEL}"], check=False)
    running = r.returncode == 0

    ip_address = ""
    if running:
        ifc = run_command(["ifconfig", _PPP_TUN_IFACE], check=False)
        m = re.search(r"inet\s+(\S+)", ifc.stdout or "")
        if m:
            ip_address = m.group(1)

    return {
        "running": running,
        "interface": _PPP_TUN_IFACE,
        "ip_address": ip_address,
        "message": "Connected" if running else "Disconnected",
    }


# ---------------------------------------------------------------------------
# Disconnect
# ---------------------------------------------------------------------------

def disconnect_pppoe() -> dict:
    """Stop the ppp(8) daemon and tear down the PPPoE session."""
    if not _on_freebsd():
        return {"ok": True, "message": "Not on FreeBSD — nothing to disconnect."}

    run_command(["pkill", "-f", f"ppp.*{_PPP_LABEL}"], check=False)
    return {"ok": True, "message": "PPPoE session disconnected."}
