"""
rtadvd_writer.py
----------------
Generates rtadvd.conf for FreeBSD base-system Router Advertisement daemon.
rtadvd sends IPv6 Router Advertisement messages so clients can autoconfigure.

Backend: rtadvd (FreeBSD base system — /usr/sbin/rtadvd)
Config:  /etc/rtadvd.conf

Public API
----------
generate_rtadvd_conf(conn)  -> str
validate_rtadvd(conn)       -> list[str]
apply_rtadvd(conn)          -> dict
get_rtadvd_status()         -> dict
"""

import ipaddress
import sys

_RTADVD_CONF_PATH = "/etc/rtadvd.conf"


def _rows(conn, sql, params=()):
    cur = conn.cursor()
    cur.execute(sql, params)
    return [dict(r) for r in cur.fetchall()]


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def validate_rtadvd(conn) -> list:
    errors = []
    ifaces = _rows(conn, "SELECT * FROM ra_settings WHERE enabled=1")
    for iface in ifaces:
        name = (iface.get("interface_name") or "").strip()
        if not name:
            errors.append("RA configuration has no interface name.")
            continue

        prefix = (iface.get("prefix") or "").strip()
        if prefix:
            try:
                net = ipaddress.ip_network(prefix, strict=False)
                if net.version != 6:
                    errors.append(f"[{name}] Prefix {prefix!r} is not an IPv6 prefix.")
                if net.prefixlen not in range(1, 128):
                    errors.append(f"[{name}] Prefix length must be 1–127.")
            except ValueError:
                errors.append(f"[{name}] Prefix {prefix!r} is not a valid IPv6 network.")

        for dns in _split_csv(iface.get("dns_servers") or ""):
            try:
                a = ipaddress.ip_address(dns)
                if a.version != 6:
                    errors.append(f"[{name}] DNS server {dns!r} is not an IPv6 address.")
            except ValueError:
                errors.append(f"[{name}] DNS server {dns!r} is invalid.")

    return errors


def _split_csv(raw: str) -> list:
    return [s.strip() for s in (raw or "").split(",") if s.strip()]


# ---------------------------------------------------------------------------
# Config generator
# ---------------------------------------------------------------------------

def generate_rtadvd_conf(conn) -> str:
    ifaces = _rows(conn, "SELECT * FROM ra_settings WHERE enabled=1 ORDER BY interface_name")
    lines = [
        "# ============================================================",
        "# Smart Shield — auto-generated rtadvd.conf",
        "# Generated by app/services/rtadvd_writer.py",
        "# Backend: rtadvd (FreeBSD base system)",
        "# DO NOT EDIT MANUALLY",
        "# ============================================================",
        "",
    ]

    for iface in ifaces:
        name     = (iface.get("interface_name") or "").strip()
        if not name:
            continue
        prefix   = (iface.get("prefix") or "").strip()
        auto     = bool(iface.get("autonomous_flag", 1))
        managed  = bool(iface.get("managed_flag", 0))
        other    = bool(iface.get("other_flag", 0))
        priority = (iface.get("router_priority") or "medium").lower()
        dns_list = _split_csv(iface.get("dns_servers") or "")
        domain   = (iface.get("domain_search") or "").strip()
        min_int  = iface.get("min_interval") or 200
        max_int  = iface.get("max_interval") or 600
        default_lifetime = iface.get("default_lifetime") or 1800

        parts = []
        parts.append(f"maxinterval#{max_int}")
        parts.append(f"mininterval#{min_int}")
        parts.append(f"lifetime#{default_lifetime}")

        # Router priority: high → 64, medium → 0 (default), low → -63
        rtpref = {"high": "64", "medium": "0", "low": "-63"}.get(priority, "0")
        parts.append(f"rtpref#{rtpref}")

        if managed:
            parts.append("managedFlag")
        if other:
            parts.append("otherConfigFlag")

        # Prefix
        if prefix:
            try:
                net  = ipaddress.ip_network(prefix, strict=False)
                plen = net.prefixlen
                addr = str(net.network_address)
                aflag = "on" if auto else "off"
                parts.append(f"addr#{addr}")
                parts.append(f"prefixlen#{plen}")
                parts.append(f"aflag#{aflag}")
            except ValueError:
                pass

        # RDNSS (RFC 5006 / 6106)
        if dns_list:
            dns_csv = ",".join(dns_list)
            parts.append(f"rdnss#{dns_csv}")
        if domain:
            parts.append(f"dnssl#{domain}")

        lines.append(f"{name}:\\")
        for i, part in enumerate(parts):
            sep = ":" if i < len(parts) - 1 else ""
            lines.append(f"    :{part}{sep}\\")
        lines[-1] = lines[-1].rstrip("\\")
        lines.append("")

    if not ifaces:
        lines.append("# No RA interfaces configured.")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Write + apply
# ---------------------------------------------------------------------------

def apply_rtadvd(conn) -> dict:
    errors = validate_rtadvd(conn)
    conf   = generate_rtadvd_conf(conn)

    if errors:
        return {"ok": False, "message": "Validation failed: " + " | ".join(errors), "conf": conf}

    if not sys.platform.startswith("freebsd"):
        return {"ok": True, "rolled_back": False,
                "message": "Non-FreeBSD — rtadvd.conf generated but not written.", "conf": conf}

    from app.services.config_file_utils import apply_with_rollback
    from app.services.service_manager import service_action, sysrc_set
    sysrc_set("rtadvd_enable", "YES")

    def _restart():
        return service_action("rtadvd", "restart")

    result = apply_with_rollback(_RTADVD_CONF_PATH, conf, _restart,
                                 validate_fn=_validate_rtadvd_conf)
    return {**result, "conf": conf}


def _validate_rtadvd_conf(tmp_path: str) -> dict:
    """Offline preflight of a staged rtadvd.conf before it goes live.

    rtadvd has no ``-t`` syntax-check mode, so this is a Python-only check: the
    file must be readable and must not end on a dangling termcap-style line
    continuation (a trailing ``\\``), which rtadvd would refuse to parse.
    """
    try:
        with open(tmp_path, encoding="utf-8") as fh:
            text = fh.read()
    except OSError as exc:
        return {"ok": False, "message": f"cannot read staged rtadvd.conf: {exc}", "output": ""}
    if text.rstrip("\n").endswith("\\"):
        return {"ok": False,
                "message": "rtadvd.conf ends on a dangling line continuation", "output": ""}
    return {"ok": True, "message": "rtadvd.conf preflight OK", "output": ""}


# ---------------------------------------------------------------------------
# Status
# ---------------------------------------------------------------------------

def get_rtadvd_status() -> dict:
    if not sys.platform.startswith("freebsd"):
        return {"running": False, "state": "dry-run", "message": "Non-FreeBSD host."}
    from app.services.service_manager import service_action
    r = service_action("rtadvd", "status")
    running = r["ok"] and "running" in r.get("message", "").lower()
    return {"running": running, "state": "running" if running else "stopped",
            "message": r.get("message", "")}
