"""
app/services/soc_portal_writer.py
----------------------------------
Owns the full SOC Team Portal lifecycle: validates the bind IP, creates a
matching virtual IP alias on the LAN interface, reloads PF so the new VIP is
reachable, then writes the nginx server block and reloads nginx.

Generated file:    /usr/local/etc/nginx/soc-portal.conf
Main nginx.conf:   includes soc-portal.conf

The VIP is stored as a row in `virtual_ips_configs` tagged with
`VIP_DESCRIPTION` so subsequent saves replace it idempotently. Disabling the
SOC portal removes the row and re-applies VIPs so the alias disappears.
"""

import ipaddress
import os
import sys

from app.config import _ss_dir

_SOC_NGINX_CONF = "/usr/local/etc/nginx/soc-portal.conf"
_DEFAULT_CERT   = os.path.join(_ss_dir("/usr/local/etc"), "ssl", "cert.pem")
_DEFAULT_KEY    = os.path.join(_ss_dir("/usr/local/etc"), "ssl", "key.pem")

VIP_DESCRIPTION = "Smart Shield — SOC portal alias"


def _safe_int(value, default: int, min_value: int, max_value: int,
              name: str) -> tuple:
    """Return ``(ok, value, error)`` for an int config field with range guard.

    Used so a malformed/out-of-range DB value (bind_port, vip_prefix) produces
    an actionable error instead of an ``int()`` crash inside the save route.
    """
    try:
        n = int(value if value is not None else default)
    except (TypeError, ValueError):
        return False, default, f"{name} must be a number"
    if n < min_value or n > max_value:
        return False, n, f"{name} must be between {min_value} and {max_value}"
    return True, n, ""


def _nginx_listen_addr(bind_ip: str, bind_port: int) -> str:
    """Return the nginx ``listen`` target, bracketing IPv6 (``[addr]:port``)."""
    ip = ipaddress.ip_address(bind_ip)
    if ip.version == 6:
        return f"[{bind_ip}]:{bind_port}"
    return f"{bind_ip}:{bind_port}"


def _cert_paths(conn, ssl_cert_id):
    """Return (cert_path, key_path) for the given certificate id."""
    if ssl_cert_id:
        try:
            row = conn.execute(
                "SELECT cert_path, key_path FROM certificates WHERE id=?",
                (ssl_cert_id,),
            ).fetchone()
            if row and row["cert_path"] and row["key_path"]:
                return row["cert_path"], row["key_path"]
        except Exception:
            pass
    return _DEFAULT_CERT, _DEFAULT_KEY


def generate_soc_nginx_block(bind_ip: str, bind_port: int,
                             cert_path: str, key_path: str) -> str:
    """Return the nginx server block as a string."""
    listen_addr = _nginx_listen_addr(bind_ip, bind_port)
    return f"""# Smart Shield — SOC Team Portal
# Auto-generated by Smart Shield. Do not edit manually.
# Regenerated from: System → SOC Portal Settings

server {{
    listen      {listen_addr} ssl;
    server_name _;

    ssl_certificate     {cert_path};
    ssl_certificate_key {key_path};

    ssl_protocols             TLSv1.2 TLSv1.3;
    ssl_ciphers               ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers on;
    ssl_session_cache         shared:SOC:5m;
    ssl_session_timeout       1d;
    ssl_session_tickets       off;

    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;
    add_header X-Frame-Options           DENY                                  always;
    add_header X-Content-Type-Options    nosniff                               always;

    # SOC portal routes only — analysts cannot reach the admin UI
    location /soc-portal/ {{
        proxy_pass         http://127.0.0.1:5000;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto https;
        proxy_read_timeout 300s;
    }}

    # Block everything else — admins must use port 443
    location / {{
        return 404;
    }}
}}
"""


def _lan_context(conn):
    """Return (lan_port, lan_ipv4_iface) or (None, None) if LAN not assigned."""
    try:
        row = conn.execute(
            "SELECT assigned_port, ipv4_address FROM lan_config WHERE id=1"
        ).fetchone()
    except Exception:
        return None, None
    if not row:
        return None, None
    port = (row["assigned_port"] or "").strip().split()[0:1]
    port = port[0] if port else ""
    cidr = (row["ipv4_address"] or "").strip()
    if not port or not cidr:
        return None, None
    try:
        return port, ipaddress.ip_interface(cidr)
    except ValueError:
        return None, None


def _remove_soc_vip(conn) -> None:
    """Delete the SOC portal VIP row (idempotent)."""
    try:
        conn.execute(
            "DELETE FROM virtual_ips_configs WHERE description=?",
            (VIP_DESCRIPTION,),
        )
        conn.commit()
    except Exception:
        pass


def _upsert_soc_vip(conn, lan_port: str, bind_ip: str, prefix: int) -> None:
    """Replace any existing SOC portal VIP row with the requested address."""
    conn.execute(
        "DELETE FROM virtual_ips_configs WHERE description=?",
        (VIP_DESCRIPTION,),
    )
    conn.execute(
        "INSERT INTO virtual_ips_configs (type, interface, address_type, address, "
        "prefix, description) VALUES (?,?,?,?,?,?)",
        ("ipalias", lan_port, "single", bind_ip, int(prefix), VIP_DESCRIPTION),
    )
    conn.commit()


def write_soc_portal_nginx_config(conn) -> dict:
    """
    Generate and write the nginx SOC portal server block.

    Full lifecycle on save:
      1. validate bind_ip is inside the LAN subnet and differs from the LAN
         primary IP,
      2. upsert the SOC VIP row in virtual_ips_configs and call apply_vips()
         so the alias goes live,
      3. reload PF so the new pass-rule for bind_ip:bind_port is loaded,
      4. write soc-portal.conf and reload nginx.

    On disable: tear all of the above down in reverse.

    Non-FreeBSD: returns a config preview without writing anything.
    """
    try:
        row = conn.execute(
            "SELECT enabled, bind_ip, bind_port, ssl_cert_id, vip_prefix "
            "FROM soc_portal_config WHERE id=1"
        ).fetchone()
    except Exception as exc:
        return {"ok": False, "message": f"DB error: {exc}", "config": ""}

    if not row:
        return {"ok": False, "message": "SOC portal config not found.", "config": ""}

    # ------------------------------------------------------------------ disabled
    if not row["enabled"]:
        _remove_soc_vip(conn)
        if sys.platform.startswith("freebsd"):
            try:
                from app.services.network_service import apply_vips
                apply_vips(conn)
            except Exception:
                pass
            try:
                import os
                if os.path.exists(_SOC_NGINX_CONF):
                    os.unlink(_SOC_NGINX_CONF)
                from app.services.service_manager import service_action
                service_action("nginx", "reload")
            except Exception:
                pass
            try:
                from app.services.pf_generator import reload_pf_rules
                reload_pf_rules(conn)
            except Exception:
                pass
        return {"ok": True, "message": "SOC portal disabled — alias and nginx config removed.", "config": ""}

    # ------------------------------------------------------------------ enabled
    bind_ip = (row["bind_ip"] or "0.0.0.0").strip()

    ok_port, bind_port, port_err = _safe_int(row["bind_port"], 8443, 1, 65535, "Bind port")
    if not ok_port:
        return {"ok": False, "message": port_err, "config": ""}

    if bind_ip == "0.0.0.0":
        return {
            "ok": False,
            "message": "Set a specific bind IP (not 0.0.0.0) — the SOC portal needs a dedicated LAN virtual IP.",
            "config": "",
        }

    try:
        bind_addr_obj = ipaddress.ip_address(bind_ip)
    except ValueError:
        return {"ok": False, "message": f"Bind IP '{bind_ip}' is not a valid IPv4/IPv6 address.", "config": ""}

    # Prefix range depends on the address family; validate after the bind IP.
    max_prefix = 32 if bind_addr_obj.version == 4 else 128
    ok_prefix, prefix, prefix_err = _safe_int(
        row["vip_prefix"] if "vip_prefix" in row.keys() else None,
        max_prefix, 0, max_prefix, "VIP prefix",
    )
    if not ok_prefix:
        return {"ok": False, "message": prefix_err, "config": ""}

    lan_port, lan_iface = _lan_context(conn)
    if not lan_port or lan_iface is None:
        return {
            "ok": False,
            "message": "LAN interface not configured — assign LAN in Interfaces first.",
            "config": "",
        }

    try:
        bind_addr_obj = ipaddress.ip_address(bind_ip)
        if bind_addr_obj not in lan_iface.network:
            return {
                "ok": False,
                "message": (
                    f"Bind IP {bind_ip} must be inside the LAN subnet {lan_iface.network} "
                    f"so it can be aliased on {lan_port}."
                ),
                "config": "",
            }
        if bind_addr_obj == lan_iface.ip:
            return {
                "ok": False,
                "message": (
                    f"Bind IP {bind_ip} must differ from the LAN interface's primary IP "
                    f"({lan_iface.ip}) — pick a free address in {lan_iface.network}."
                ),
                "config": "",
            }
    except ValueError as exc:
        return {"ok": False, "message": f"Subnet check failed: {exc}", "config": ""}

    cert_path, key_path = _cert_paths(conn, row["ssl_cert_id"])
    config = generate_soc_nginx_block(bind_ip, bind_port, cert_path, key_path)

    if not sys.platform.startswith("freebsd"):
        # Record the VIP row (idempotent) but do no live work off-FreeBSD.
        try:
            _upsert_soc_vip(conn, lan_port, bind_ip, prefix)
        except Exception as exc:
            return {"ok": False, "message": f"Failed to record SOC VIP: {exc}", "config": config}
        return {
            "ok": True,
            "message": (
                f"Config preview (non-FreeBSD host — not written to disk). "
                f"Would alias {bind_ip}/{prefix} on {lan_port}."
            ),
            "config": config,
        }

    # Persist the VIP row first so pf_generator and apply_vips both see it, then
    # run the live lifecycle. If ANY later step fails, roll the VIP row back so
    # a failed save never leaves a stale SOC alias in the DB.
    vip_recorded = False
    try:
        _upsert_soc_vip(conn, lan_port, bind_ip, prefix)
        vip_recorded = True

        # Bring the alias online.
        from app.services.network_service import apply_vips
        vip_result = apply_vips(conn)
        if not vip_result.get("ok"):
            raise RuntimeError(
                f"Failed to add VIP {bind_ip}/{prefix} on {lan_port}: "
                f"{vip_result.get('message', '')}")

        # Reload PF so the new pass-rule for the SOC VIP is loaded.
        from app.services.pf_generator import reload_pf_rules
        pf_result = reload_pf_rules(conn)
        if not pf_result.get("ok"):
            raise RuntimeError(
                f"VIP added but PF reload failed: {pf_result.get('message', '')}")

        # Write the nginx vhost.
        from app.services.config_file_utils import atomic_write
        atomic_write(_SOC_NGINX_CONF, config, mode=0o644)

        # Regenerate the admin vhost too so /soc-portal/* is blocked on the admin
        # LAN IP (analysts must use the dedicated SOC IP). apply_nginx writes
        # nginx.conf and reloads, so the SOC vhost we just wrote also takes
        # effect from the same reload (single reload, no race).
        from app.services.nginx_writer import apply_nginx
        admin_result = apply_nginx(conn)
        if not admin_result.get("ok"):
            raise RuntimeError(
                "SOC config written but admin nginx regen failed: "
                f"{admin_result.get('message', '')}")
    except Exception as exc:
        # Roll back the VIP row + re-apply VIPs so the alias disappears.
        if vip_recorded:
            _remove_soc_vip(conn)
            try:
                from app.services.network_service import apply_vips
                apply_vips(conn)
            except Exception:
                pass
        return {"ok": False, "message": str(exc), "config": config}

    return {
        "ok": True,
        "message": (
            f"SOC portal now accessible at https://{bind_ip}:{bind_port}/soc-portal/ "
            f"(alias added on {lan_port}). Admin vhost regenerated to block "
            "/soc-portal/* on the admin IP."
        ),
        "config": config,
    }
